### PR TITLE
Block the user without authorization from the whole application

### LINKED ISSUE #455: [Bug]: When a user is not allowed access -- they still can click on the Jupyter tile
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I do not have allowed access from `OdhDashboardConfig.spec.groupsConfig.allowedGroups`, we still see the Jupyter tile... clicking on it will get you a 404 page. This is a gap we need to correct.

Either they have permissions to access it or not. We shouldn't dangle it and then tell them about it later.

### Expected Behavior

Not to have access to the Jupyter tile when I do not have allowed access to use it.

### Steps To Reproduce

1. Have a config without the user in `allowedGroups` -- don't use `system:authenticated`
2. See the tile in the Enabled/home screen
3. Click on it -- if you're not allowed, you'll get a 404 -- if you are allowed you will get the SpawnerPage

### Workaround (if any)

Grant them access -- but none to remove access to the tile today.

### OpenShift Infrastructure Version

_No response_

### Openshift Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
2.1
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #455 

## Description

Deleted some unused files. Now if the user is not allowed, it will not see the Nav as well as any page, we will only show them the page of the Unauthorized User.

Screen Shot 2022-11-01 at 4 54 20 PM

(Omit the nav icon on the top left corner, it won't be there. This screenshot is only used for display the page content result)

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: frontend/src/app/AppRoutes.tsx [hunk 1]
```diff
@@ -31,21 +32,25 @@ const AppRoutes: React.FC = () => {
...
-        <Route path="/explore" element={<ExploreApplications />} />
-        <Route path="/resources" element={<LearningCenterPage />} />
-        {isAllowed && <Route path="/projects/*" element={<ProjectViewRoutes />} />}
-        {isAllowed && <Route path="/notebookController/*" element={<NotebookController />} />}
-        {isAllowed && (
-          <Route
-            path="/notebook/:namespace/:notebookName/logout"
-            element={<NotebookLogoutRedirectPage />}
-          />
+        {isAllowed ? (
```
Comment (andrewballantyne) [inline frontend/src/app/AppRoutes.tsx:35]: Can you avoid doing large conditionals for a single point -- Wouldn't it work if we just use the exit early pattern? I don't think we _need_ the ApplicationPage fallback either or even the suspense as there is no logic here.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]

**Review by andrewballantyne — APPROVED** [review]

**Comment by andrewballantyne** [comment]
Holding for UX feedback.

cc @kywalker-rh
