### PR TITLE
Refetch notebook route if error

### LINKED ISSUE #767: [Bug]: Make sure the Workbench Route has refresh tolerance
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we fetch the workbench route, if it fails we flat out error out.

### Expected Behavior

We should fetch again if it fails. Once we have it, there is no need to keep fetching.

When we error out (we'll probably need to force / fake an error to test) we should be able to get a tooltip off the error icon (put it outside of the disable button)

### Steps To Reproduce

Not sure it is easy to reproduce, seems to happen under load.

https://issues.redhat.com/browse/RHODS-5819

### Workaround (if any)

Refresh / reload the page by navigating away and back

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
2.4.0
```

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
## Description

Closes #767 
If error, re-fetch the notebook route in 1 second until we get the notebook route.
Also, move the error icon outside of the link button, so the user could see the error message when hovering over it.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: frontend/src/pages/projects/notebook/useRouteForNotebook.ts [hunk 1]
```diff
@@ -13,15 +13,22 @@ const useRouteForNotebook = (
...
+      getRoute(routeName, routeNamespace)
+        .then((route) => {
+          setRoute(`https://${route.spec.host}/notebook/${routeNamespace}/${routeName}`);
+          setLoaded(true);
+        })
+        .catch((e) => {
+          setLoadError(e);
+          setLoaded(true);
+          watchHandle = setTimeout(watchRoute, 1000);
+        });
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/notebook/useRouteForNotebook.ts:28]:
```suggestion
      getRoute(routeName, routeNamespace)
        .then((route) => {
          setRoute(`https://${route.spec.host}/notebook/${routeNamespace}/${routeName}`);
          setLoaded(true);
        })
        .catch((e) => {
          setLoadError(e);
          watchHandle = setTimeout(watchRoute, 1000);
        });
```
Let's just do away with the loaded state flipping -- it's goofy to go back and forth like this.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
/approve

I do not like the flipping of loaded state in interval loops -- it just causes the UI to do weird things over the 100-200ms call duration... flickers in the UI are common because of this.

**Review by andrewballantyne — APPROVED** [review]
