### PR TITLE
Refresh data connections when deploying model on project details page

### LINKED ISSUE #1215: [Bug]: Deploying Models doesn't refresh for new connections
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When inside the project details and you deploy a Model Serving model using create a new data connection, the model will appear but the data connection does not for several seconds.

### Expected Behavior

We should refresh the Data Connection list so it refreshes relatively fast.

### Steps To Reproduce

1. Go to a project
2. Have a Model server
3. Deploy a Model into it
4. Make sure you create a NEW data connection

On submit, you will wait a brief moment and the auto refresh will pop the data connection into the table.

### Workaround (if any)

Navigate away and back.

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
Dashboard: v2.9.1
```

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1215 

## Description

Simply refresh the data connections. Also, cleaned up the code a little because we have context, we don't need to pass all the values to the table. What's more, the table will sort inside it, we only need to pass `defaultSortColumn`.

## How Has This Been Tested?

1. Go to project details page
2. Try to deploy a model with a new data connection
3. See if the data connection appears immediately when the model is deployed

## Test Impact

N/A, it's only a network call refreshing thing.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx [hunk 1]
```diff
@@ -63,12 +63,7 @@ const ServingRuntimeList: React.FC = () => {
           />
         }
       >
-        <ServingRuntimeTable
```
Comment (lucferbux) [inline frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx:66]: Ok, I can agree with this, kinda weird that part of the rendered data is fetched with  context and the other part with props, I can see we either do one thing or another.

**Review by lucferbux — APPROVED** [review]
/lgtm

Tested and it's working as expected, nice to see the refactor in sorting but not fully convinced of removing all props, I would say is the best approach but I'm not sure if I'm happy with it.

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx (hunk 1 above)
Comment (lucferbux) [reply frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx:66]: Yes, what I meant with that is that we are supposed to have "pure" components without context data being rendered, I guess that in this case, since this component is targeted for an specific page with no intention of using it outside projects it should be fine to just use contexts.
