### PR TITLE
Use sync preferred project when switching to global model serving page

### LINKED ISSUE #2137: [Bug]: Improve global model serving project selection
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

main

### Current Behavior

Currently, when you go to the global model serving the page from a project, it always lands on the `All projects` selection.

### Expected Behavior

It should land on the corresponding project selection when you go to the model serving page from a project.

### Steps To Reproduce

1. Go to any data science project
2. Click on `Model Serving` in the side nav
3. It will land on the empty page with the project selection `All projects`

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #2137 

## Description

1. When you switch between the navs (projects, pipelines, model serving), the preferred project is always remembered and synced up
2. When you choose `All projects` on the global model serving page, the preferred project is set to `null` (We don't have that dropdown selection on the pipelines page)
3. Remove the filter label so you could select all the available projects on the global model serving page, but not only the dashboard projects
4. Fix some nits from https://github.com/opendatahub-io/odh-dashboard/pull/2123

## How Has This Been Tested?

1. Go to the projects page
2. Get into any project
3. Click on the model serving on the side nav
4. You should be able to land on the page with the same selection as the project you just entered
5. Go to the pipelines page, you can see the selection is kept
6. Select `All projects` on the global model serving page
7. Make sure everything works

## Test Impact

N/A, this needs e2e test setup IMO.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx [hunk 1]
```diff
@@ -58,16 +60,20 @@ const ModelServingGlobal: React.FC = () => {
...
-        empty: true,
-        emptyStatePage: (
-          <InvalidProject
-            namespace={namespace}
-            getRedirectPath={(namespace) => `/modelServing/${namespace}`}
-          />
-        ),
-      };
+    if (namespace) {
+      if (!currentProject) {
```
Comment (andrewballantyne) [inline frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx:64]: Why this change... you created a gap in the if-statement... if true, then false... nothing happens instead of taking preferred.

Comment (andrewballantyne) [reply frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx:64]: Test this via a direct url change

Comment (andrewballantyne) [reply frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx:64]: It's fine

**Comment by DaoDaoNoCode** [comment]
/hold
Do not merge until #2135 is fixed because this change will make the performance issue worse.

**Review by andrewballantyne — COMMENTED** [review]
Conceptually this is fine by me...

There is a performance issue that will prevent me from approving here. It is a separate issue, but this will expose it more.

File: frontend/src/concepts/projects/ProjectSelector.tsx [hunk 2]
```diff
@@ -54,10 +53,11 @@ const ProjectSelector: React.FC<ProjectSelectorProps> = ({
                 key={'all-projects'}
                 onClick={() => {
                   setDropdownOpen(false);
-                  onSelection({ metadata: { name: '' } } as ProjectKind);
+                  onSelection('');
```
Comment (lucferbux) [inline frontend/src/concepts/projects/ProjectSelector.tsx:56]: Yes, this is probably better.

**Review by lucferbux — COMMENTED** [review]
This approach is better, I'm gonna test it later with my fix to see if helps

**Review by lucferbux — APPROVED** [review]
/lgtm
