### PR TITLE
Modify logout and control panel redirect for project notebooks

### LINKED ISSUE #808: [Bug]: Workbench logout lands on broken dashboard page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When logging out of the Workbenches in the data science projects UI, the redirect link attempts to use the Jupyter route and fails to find the associated notebook the hangs on the spinner.

### Expected Behavior

We should have it redirect to the project dashboard and present an alert or modal (UX needed).

Leading theory:
- Return to the details page of the Project it is contained in
- Prompt a notification alert in the top right saying something like "Logged out of `<workbench name>`"

Needs UX to confirm. cc @kywalker-rh 

### Steps To Reproduce

1. Have a project
2. Create a workbench & wait for it to start
3. Open it up
4. Once inside, File => Logout

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
2.5.0
```

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
## Description

Closes #808 
There is no way to change the text Hub Control Panel, it's hardcoded in JupyterLab https://github.com/jupyterlab/jupyterlab/blob/master/packages/hub-extension/src/index.ts#L74-L80
The logout success prompt will be triggered twice, have no idea why, left a comment and waiting for reviews.

## How Has This Been Tested?

Create a notebook in DSG, login to the notebook, and try to click the logout and hub control panel button.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx [hunk 1]
```diff
@@ -24,10 +33,40 @@ const NotebookLogoutRedirect: React.FC = () => {
...
+      cancelled = true;
+    };
+  }, [namespace, notebookName, navigate, notification, notebookNamespace]);
+
+  React.useEffect(() => {
+    if (namespace && notebookName && namespace !== notebookNamespace) {
+      if (loaded) {
+        if (error) {
+          notification.error(`Error when logging out ${notebookName}`, error.message);
+          navigate(`/projects/${namespace}`);
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx:52]:
```suggestion
          navigate(`/projects/${namespace}?notebookLogout=${notebookName}`);
```

File: frontend/src/pages/projects/screens/detail/ProjectDetails.tsx [hunk 2]
```diff
@@ -27,6 +29,16 @@ const ProjectDetails: React.FC = () => {
...
     dashboardConfig.spec.dashboardConfig.disableModelServing,
   );
+  const queryParams = useQueryParams();
+  const notebookLogout = queryParams.get('notebook_logout');
+  const notification = useNotification();
+
+  // TODO: this will be triggered twice, don't know why
+  React.useEffect(() => {
+    if (notebookLogout) {
+      notification.success(`Logout workbench successfully`);
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/ProjectDetails.tsx:39]: RE: my other comment

Remove the search param from the URL here. 
Docs: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/delete

File: frontend/src/pages/projects/screens/detail/ProjectDetails.tsx [hunk 3]
```diff
@@ -27,6 +29,16 @@ const ProjectDetails: React.FC = () => {
...
+    }
+  }, [notebookLogout, notification]);
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/ProjectDetails.tsx:41]: make a custom hook -- this is all one thing and shouldn't be so inline with a component. Get into the habit of making custom hooks when you have isolated & coupled functionality.

File: frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx [hunk 4]
```diff
@@ -24,10 +33,40 @@ const NotebookLogoutRedirect: React.FC = () => {
...
+        } else if (routeLink) {
+          const location = new URL(routeLink);
+          window.location.href = `${location.origin}/oauth/sign_out`;
+        }
+      }
+    }
+  }, [
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx:59]: You'll want to cancel this hook too on updates.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]

File: frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx (hunk 1 above)
Comment (andrewballantyne) [reply frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx:52]: Oops, was rushing over the code -- this is not needed

File: frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts [hunk 5]
```diff
@@ -0,0 +1,18 @@
+import * as React from 'react';
+import { useSearchParams } from 'react-router-dom';
+import useNotification from '../../../../utilities/useNotification';
+
+const useCheckLogoutParams = (): void => {
+  const [queryParams, setQueryParams] = useSearchParams();
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts:6]: Hah, did not know about this. Neat.

File: frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts [hunk 6]
```diff
@@ -0,0 +1,18 @@
...
+  const notification = useNotification();
+
+  React.useEffect(() => {
+    if (queryParams.get('notebookLogout')) {
+      notification.success(`Logout workbench successfully`);
```
[the remark this answers is not in the document]
Comment (DaoDaoNoCode) [reply frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts:11]: I wanted to, but I can only show the k8s name instead of the display name unless we fetch the Notebook object here.

File: frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+    const notebookLogout = queryParams.get('notebookLogout');
+    if (notebookLogout) {
+      const notebook = notebooks.find((n) => n.notebook.metadata.name === notebookLogout);
+      if (notebook?.notebook) {
+        notification.success(
+          `Logout workbench "${getNotebookDisplayName(notebook.notebook)}" successfully`,
+        );
+        queryParams.delete('notebookLogout');
+        setQueryParams(queryParams);
+      }
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts:24]: What if it's loaded and you can't find it? Perhaps we put an error case here too? 

Something like:
```
} else if (loaded) {
  notification.error('Error logging out', 'Unable to locate notebook to finalize logout');
  // remove query param
}
```

**Review by andrewballantyne — CHANGES_REQUESTED** [review]

File: frontend/src/api/network/notebooks.ts [hunk 8]
```diff
@@ -115,7 +115,7 @@ const assembleNotebook = (data: StartNotebookData, username: string): NotebookKi
       annotations: {
         'openshift.io/display-name': notebookName,
         'openshift.io/description': description || '',
-        'notebooks.opendatahub.io/oauth-logout-url': `${origin}/notebookController/${translatedUsername}/home`,
+        'notebooks.opendatahub.io/oauth-logout-url': `${origin}/projects/${projectName}?notebookLogout=${notebookName}`,
```
Comment (andrewballantyne) [inline frontend/src/api/network/notebooks.ts:118]:
```suggestion
        'notebooks.opendatahub.io/oauth-logout-url': `${origin}/projects/${projectName}?notebookLogout=${notebookId}`,
```

This needs to be the k8s name

File: frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+
+  React.useEffect(() => {
+    const deleteLogoutParam = () => {
+      queryParams.delete('notebookLogout');
+      setQueryParams(queryParams);
+    };
+    if (notebookLogout) {
+      if (notebook) {
+        notification.success(
+          `Logout workbench "${getNotebookDisplayName(notebook.notebook)}" successfully`,
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts:25]:
```suggestion
          `Logged out of workbench "${getNotebookDisplayName(notebook.notebook)}" successfully`,
```

**Review by andrewballantyne — APPROVED** [review]
Baring the one tiny text change, this is good to merge.

/approve
/hold
