### PR TITLE
Prevent download of empty files in Pipeline Logs

### LINKED ISSUE #2226: [Bug]: Prevent downloading empty files
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

f/pipelines-enhancement 

### Current Behavior

When you have a completed pod with no logs, the download functionality still downloads an empty file.

### Expected Behavior

Prevent downloading an empty file

### Steps To Reproduce

1. Run any pipeline 
3. Go to the `Logs` tab
4. Go to any node which has completed execution but has no logs 
5. Click on `Download` 

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

Chrome

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by manaswinidas**
JIRA: [RHOAIENG-259](https://issues.redhat.com/browse/RHOAIENG-259)

## Description

This PR : 
- Prevents downloading empty log files
- Some changes to align with mocks
- Handles small screen "Download" button for pods with a single step 
- Add functionality to view raw logs (part of https://github.com/opendatahub-io/odh-dashboard/issues/1814)
- Code refactor
Screenshot from 2023-11-24 20-36-16

GIF for raw logs:

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/3bc7459a-b192-4c8a-9185-7064833f3634

Screenshots for view raw logs and disabled and enabled states of both Raw logs and Download button:

Enabled state: 

Screenshot 2023-11-30 at 7 36 07 PM

Disabled: 
Screenshot 2023-11-30 at 7 50 23 PM

Small screen:
Screenshot 2023-11-30 at 8 06 31 PM

## How Has This Been Tested?

1. Run any pipeline
2. Go to the Logs tab
3. Go to any node that has completed execution but has no logs
4. Check that you see "No logs available" and the "Download" button is disabled

## Test Impact

Added tests to check whether the drawer opens on clicking the node of a pipeline run

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [X] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 1]
```diff
@@ -105,7 +98,7 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
   } else if (logs) {
     data = logs;
   } else {
-    data = 'No content';
+    data = 'No logs available';
```
Comment (manaswinidas) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:101]: Adhering to [Case 9 of the mocks](https://www.figma.com/proto/rJjOtl3nxpW6BAcl0MZr4y/Pipeline-log-viewer?page-id=62%3A1895&type=design&node-id=426-1918&viewport=344%2C-2019%2C0.11&t=3XnKD7cO6bo81JQW-1&scaling=min-zoom&starting-point-node-id=624%3A2327&show-proto-sidebar=1)

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 2]
```diff
@@ -215,9 +184,9 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
                   variant="link"
                   aria-label="Download current step log"
                   icon={<DownloadIcon />}
-                  isDisabled={!canDownload}
+                  isDisabled={!canDownload || logs === null || logs === ''}
                 >
-                  Download
+                  {isSmallScreen() ? 'Download' : null}
```
Comment (manaswinidas) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:189]: Show only the icon in case of small screens for logs having single step.

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 3]
```diff
@@ -178,35 +171,11 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
...
-                    <Truncate
-                      content={isSmallScreen() ? 'Download all step logs' : 'All step logs'}
-                    />
-                  </DropdownItem>,
-                ]}
+              <DownloadDropdown
+                onDownload={onDownload}
+                onDownloadAll={onDownloadAll}
+                isSmallScreen={isSmallScreen()}
+                isSingleStepLogsEmpty={logs === null || logs === ''}
```
Comment (manaswinidas) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:178]: @yih-wang I remember you bringing up an empty file download if there are no logs in [this comment](https://github.com/opendatahub-io/odh-dashboard/pull/1724#issuecomment-1700660641), currently, I'm disabling the download button(single step) if there is are no logs to prevent downloading empty files.
Screenshot from 2023-11-24 20-36-16
In the case of multi-steps, the Download Dropdown is enabled but only the dropdown item corresponding to single-step logs(which is empty) is disabled.

Comment (manaswinidas) [reply frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:178]: Another way to handle this maybe to just allow the download and giving a warning that they might be downloading an empty file.

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 4]
```diff
@@ -133,7 +126,7 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
               )}
               <SplitItem>
                 <SimpleDropdownSelect
-                  isDisabled={podContainers.length === 0}
+                  isDisabled={podContainers.length === 0 || podContainers.length === 1}
```
Comment (manaswinidas) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:129]: Adhering to the [initial mocks](https://www.figma.com/proto/rJjOtl3nxpW6BAcl0MZr4y/Pipeline-log-viewer?page-id=62%3A1895&type=design&node-id=272-2932&viewport=664%2C-1095%2C0.23&t=80ExnogduAcwD3kx-1&scaling=min-zoom&starting-point-node-id=260%3A2386)

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx (hunk 3 above)
Comment (yih-wang) [reply frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:178]: @manaswinidas What you have now (disabling the download action for the step that doesn't have logs) looks good.

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 5]
```diff
@@ -154,9 +147,7 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
               onClick={() => setIsPaused(!isPaused)}
               isDisabled={!!error}
             >
-              {error ? (
-                'Error loading logs'
-              ) : !logsLoaded ? (
```
Comment (manaswinidas) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:159]: Aligning with mocks

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 6]
```diff
@@ -215,9 +182,9 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
                   variant="link"
                   aria-label="Download current step log"
                   icon={<DownloadIcon />}
-                  isDisabled={!canDownload}
+                  isDisabled={!canDownload || logs === null || logs === ''}
                 >
-                  Download
+                  {isSmallScreen() ? null : 'Download'}
```
Comment (manaswinidas) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:187]: small screen "Download" button for single step logs

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 7]
```diff
@@ -154,72 +148,62 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
...
+                  newTab?.document.write(`<pre>${logs}</pre>`);
+                }}
+                variant="link"
+                aria-label="View raw logs"
+                icon={<OutlinedWindowRestoreIcon />}
+                isDisabled={logs === null || logs === ''}
+              >
+                {!isSmallScreen() ? 'Raw' : null}
+              </Button>
+            </Tooltip>
```
Comment (manaswinidas) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:182]: @yih-wang The view raw logs functionality is added here. It is reduced to an icon on a small screen and is disabled when there are no logs. Here is a GIF for your reference.

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/e0db2585-1147-444f-bb7a-76444b91357c

Screenshots:

Enabled state: 

Screenshot 2023-11-30 at 7 36 07 PM

Disabled: 
Screenshot 2023-11-30 at 7 50 23 PM

Small screen:
Screenshot 2023-11-30 at 8 06 31 PM

**Review by DaoDaoNoCode — CHANGES_REQUESTED** [review]
The `download all step logs` link button in the alert should also be disabled when the file is empty. Otherwise, I can still download empty files.

Screenshot 2023-12-11 at 3 23 32 PM

**Comment by manaswinidas** [comment]
@DaoDaoNoCode Oh yes, I missed this. Thanks for pointing this out. Added now.
Screenshot 2023-12-12 at 8 26 04 PM

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 8]
```diff
@@ -130,18 +125,18 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
...
                       <TextListItem component={TextListItemVariants.dt}>Step</TextListItem>
                     </TextContent>
                   </Bullseye>
                 </SplitItem>
-              )}
+              ) : null}
               <SplitItem>
                 <SimpleDropdownSelect
-                  isDisabled={podContainers.length === 0}
+                  isDisabled={podContainers.length === 0 || podContainers.length === 1}
```
Comment (dpanshug) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:139]:
```suggestion
                  isDisabled={podContainers.length <= 1}
```

**Review by dpanshug — CHANGES_REQUESTED** [review]
Disabling the `download all step logs` should not depend on the selected step.

When selected step with logs, the button is enabled.

Screenshot from 2023-12-18 12-46-15

When selected step without logs, the button gets disabled.

Screenshot from 2023-12-18 12-46-27

the link button should be enabled for all steps, if one step has a log

**Review by DaoDaoNoCode — COMMENTED** [review]
Code lgtm, needs to run through it tomorrow to test. My internet is still down now for the whole afternoon so I got very limited internet access.

**Review by DaoDaoNoCode — APPROVED** [review]
Tested, works fine.
/lgtm

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx [hunk 9]
```diff
@@ -0,0 +1,69 @@
...
+  isSmallScreen,
+  isSingleStepLogsEmpty,
+}) => {
+  const [isDownloadDropdownOpen, setIsDownloadDropdownOpen] = React.useState(false);
+
+  return isSmallScreen ? (
+    <Dropdown
+      toggle={<KebabToggle onToggle={() => setIsDownloadDropdownOpen(!isDownloadDropdownOpen)} />}
+      isOpen={isDownloadDropdownOpen}
+      isPlain={isSmallScreen}
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx:29]:
```suggestion
      isPlain
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx [hunk 10]
```diff
@@ -0,0 +1,69 @@
...
+      dropdownItems={[
+        <DropdownItem
+          isDisabled={isSingleStepLogsEmpty}
+          key="current-container-logs"
+          onClick={onDownload}
+        >
+          <Truncate content={'Download current step log'} />
+        </DropdownItem>,
+        <DropdownItem key="all-container-logs" onClick={onDownloadAll}>
+          <Truncate content={'Download all step logs'} />
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx:39]: This will cause the linter to fail when this is brought into `main`.
```suggestion
          <Truncate content="Download all step logs" />
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx [hunk 11]
```diff
@@ -0,0 +1,69 @@
...
+        </DropdownToggle>
+      }
+      isOpen={isDownloadDropdownOpen}
+      dropdownItems={[
+        <DropdownItem
+          isDisabled={isSingleStepLogsEmpty}
+          key="current-container-logs"
+          onClick={onDownload}
+        >
+          <Truncate content={'Current step log'} />
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx:60]:
```suggestion
          <Truncate content="Current step log" />
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx [hunk 12]
```diff
@@ -0,0 +1,69 @@
...
+        </DropdownItem>,
+        <DropdownItem key="all-container-logs" onClick={onDownloadAll}>
+          <Truncate content={'All step logs'} />
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx:63]:
```suggestion
          <Truncate content="All step logs" />
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 13]
```diff
@@ -121,6 +115,7 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
           <LogsTabStatus
             loaded={loaded}
             error={error}
+            isLogsNotAvailable={logs === null || logs === ''}
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:118]: type for `logs` is a `string`. Doesn't say it can be `null`. Is the type incorrect?

We always want to treat `null` and `undefined` as the same value unless there's a specific reason not to.
Here i think you can simplify this to:
```suggestion
            isLogsNotAvailable={!logs}
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 14]
```diff
@@ -130,18 +125,18 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
         <Split hasGutter isWrappable>
           <SplitItem>
             <Split hasGutter>
-              {isSmallScreen() ? null : (
+              {!isSmallScreen() ? (
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:128]: I know this is already existed. But why is `isSmallScreen` a function?

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 15]
```diff
@@ -163,73 +158,62 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
...
+            <Tooltip position="top" content={<div>View raw logs</div>}>
+              <Button
+                onClick={() => {
+                  const newTab = window.open();
+                  newTab?.document.write(`<pre>${logs}</pre>`);
+                }}
+                variant="link"
+                aria-label="View raw logs"
+                icon={<OutlinedWindowRestoreIcon />}
+                isDisabled={podContainers.length === 1 && (logs === null || logs === '')}
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:188]:
```suggestion
                isDisabled={podContainers.length === 1 && !logs}
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 16]
```diff
@@ -163,73 +158,62 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
...
-            ) : (
+            {podContainers.length <= 1 ? (
               <Tooltip position="top" content={<div>Download current step log</div>}>
                 <Button
                   onClick={onDownload}
                   variant="link"
                   aria-label="Download current step log"
                   icon={<DownloadIcon />}
-                  isDisabled={!canDownload}
+                  isDisabled={!canDownload || logs === null || logs === ''}
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:205]:
```suggestion
                  isDisabled={!canDownload || !logs}
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 17]
```diff
@@ -163,73 +158,62 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
...
-                  Download
+                  {!isSmallScreen() ? 'Download' : null}
                 </Button>
               </Tooltip>
+            ) : (
+              <DownloadDropdown
+                onDownload={onDownload}
+                onDownloadAll={onDownloadAll}
+                isSmallScreen={isSmallScreen()}
+                isSingleStepLogsEmpty={logs === null || logs === ''}
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:215]:
```suggestion
                isSingleStepLogsEmpty={!logs}
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx [hunk 18]
```diff
@@ -7,12 +7,19 @@ import {
 
 type LogsTabStatusProps = {
   error?: Error;
+  isLogsNotAvailable?: boolean;
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx:10]: Prefer a positive boolean prop:
```suggestion
  isLogsAvailable?: boolean;
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx [hunk 19]
```diff
@@ -0,0 +1,69 @@
...
+      toggle={<KebabToggle onToggle={() => setIsDownloadDropdownOpen(!isDownloadDropdownOpen)} />}
+      isOpen={isDownloadDropdownOpen}
+      isPlain={isSmallScreen}
+      dropdownItems={[
+        <DropdownItem
+          isDisabled={isSingleStepLogsEmpty}
+          key="current-container-logs"
+          onClick={onDownload}
+        >
+          <Truncate content={'Download current step log'} />
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx:36]:
```suggestion
          <Truncate content="Download current step log" />
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 20]
```diff
@@ -163,73 +158,62 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
...
+                  ) : (
+                    <>
+                      <PauseIcon /> {isSmallScreen() ? 'Pause' : 'Pause refreshing'}
+                    </>
+                  ))}
               </Button>
             )}
           </SplitItem>
           <SplitItem isFilled style={{ textAlign: 'right' }}>
+            <Tooltip position="top" content={<div>View raw logs</div>}>
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:179]:
```suggestion
            <Tooltip position="top" content="View raw logs">
```

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx [hunk 21]
```diff
@@ -38,7 +45,7 @@ const LogsTabStatus: React.FC<LogsTabStatusProps> = ({ error, loaded, refresh, o
         latest {LOG_TAIL_LINES} lines. Exceptionally long lines are abridged. To view the full log
         for this task, you can{' '}
         <Button
-          isDisabled={!onDownload}
+          isDisabled={!onDownload || isLogsNotAvailable}
           variant="link"
           isInline
           component="span"
```
Comment (christianvogt) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx:51]: I don't see why this `Button` uses `component="span"`. An inline button should work.

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx (hunk 14 above)
Comment (manaswinidas) [reply frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx]: Thanks for pointing this out. Changed.

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 22]
```diff
@@ -121,6 +115,7 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
           <LogsTabStatus
             loaded={loaded}
             error={error}
+            isLogsAvailable={podContainers.length === 1 && !logs}
```
Comment (DaoDaoNoCode) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:118]: If you change the name to `isLogsAvailable` from `isLogsNotAvailable`, then you should pass the correct boolean to reflect the change.

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx [hunk 23]
```diff
@@ -38,10 +45,9 @@ const LogsTabStatus: React.FC<LogsTabStatusProps> = ({ error, loaded, refresh, o
         latest {LOG_TAIL_LINES} lines. Exceptionally long lines are abridged. To view the full log
         for this task, you can{' '}
         <Button
-          isDisabled={!onDownload}
+          isDisabled={!onDownload || isLogsAvailable}
```
Comment (DaoDaoNoCode) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx:48]: Here the same, developers will feel confused why the button is disabled when `isLogsAvailable`. You should change it to `!isLogsAvailable` after you change the prop passed into this component.

**Review by DaoDaoNoCode — CHANGES_REQUESTED** [review]

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx (hunk 22 above)
Comment (manaswinidas) [reply frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx]: Agreed. I just changed this. Thanks.

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx [hunk 24]
```diff
@@ -121,6 +115,7 @@ const LogsTabForPodName: React.FC<{ podName: string }> = ({ podName }) => {
           <LogsTabStatus
             loaded={loaded}
             error={error}
+            isLogsAvailable={podContainers.length !== 1 && logs !== ''}
```
Comment (DaoDaoNoCode) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx:118]: I feel the logic is not correct here... if you simply do `!(podContainers.length === 1 && !logs)` you will get `podContainers.length !==1 || !!logs`

**Review by DaoDaoNoCode — APPROVED** [review]
/lgtm
