### PR TITLE
Check user permissions before promoting data science projects

### LINKED ISSUE #963: [Bug]: Improve Namespace Endpoint
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We added a promote to dashboard endpoint for projects/namespaces a while ago in https://github.com/opendatahub-io/odh-dashboard/issues/744. 

Currently there is no check or balance involved in how this is used. We should look to check the oauth's user's token for the access to the namespace before modifying it.

### Expected Behavior

Only the users who can edit the namespace can promote it.

### Steps To Reproduce

You'll need to make the api call via the console/another tool or add a dummy button to test this functionality with a non-dashboard project. If it's already in the dashboard, modifications are not hugely needed to be blocked -- wouldn't hurt to reject it in any case.

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
Dashboard: v2.5.0
```

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #963 

## Description

We can use [SelfSubjectReviewAccess](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1/) to check the permissions of a specific user to some resources. For this issue, we need to check the update permission to the given project, but everything needs to be done at the backend so we need to call `passThrough` and the k8s API endpoint directly before the service account do the labels patching.

## How Has This Been Tested?

Prerequisite: You must have 2 accounts on the cluster, 1 as the cluster admin (ADMIN) and one as the regular user (USER).
1. Deploy the image of this PR `pr-991` to your dashboard pod
2. Create a regular project (non-DSG project) using the OpenShift console or the oc command with the ADMIN account
3. Login to the dashboard with both the ADMIN account and USER account and go to the URL `${dashboardURL}/api/namespaces/${projectYouCreated}/1`, this command will patch a label and promote the project to a model serving project
4. Check the result of these 2 accounts, for ADMIN, it should return `{ applied: true }`, and for the USER account, it should return a 403 error
5. Add a RoleBinding to the namespace, the role is `admin` and the subject is the regular user, which gives the regular user admin permission to the project
6. Use the USER account to request that URL again, you will see `{ applied: true }`
7. Delete the RoleBinding and create a new RoleBinding but change the role to `edit`
8. Repeat step 6 and you will find it returns a 403 error again
9. Use the USER account to create a new project as in step 2, and test the permission in the dashboard as in steps 3 and 4

Follow the test instructions in the last section, you will see this if you have admin permission for the project you are trying to promote:
Screenshot 2023-03-09 at 4 22 40 PM

And the project will be promoted:
Screenshot 2023-03-09 at 4 26 02 PM

If you don't have permission:
Screenshot 2023-03-09 at 4 25 11 PM

## Test Impact

N/A, this needs to be tested on the cluster since we need the service account.

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

File: backend/src/routes/api/namespaces/namespaceUtils.ts [hunk 1]
```diff
@@ -16,6 +18,36 @@ export const applyNamespaceChange = (
       400,
     );
   }
+  const kc = fastify.kube.config;
+  const cluster = kc.getCurrentCluster();
+
+  const selfSubjectAccessReviewResult = await passThrough<V1SelfSubjectAccessReview>(
```
Comment (lucferbux) [inline backend/src/routes/api/namespaces/namespaceUtils.ts:24]: Small nit, should we wanna try/catch it to log an internal error?

I was reviewing the passThrough method and the logic is covering most of the errors, but it seems off that we are not error handling this specific call.

File: backend/src/routes/api/namespaces/namespaceUtils.ts [hunk 2]
```diff
@@ -16,6 +18,36 @@ export const applyNamespaceChange = (
...
+            namespace: name,
+          },
+        },
+      }),
+    },
+    true,
+  );
+
+  if (!selfSubjectAccessReviewResult.status.allowed) {
+    throw createCustomError('Forbidden', "You don't have the access to update the namespace", 403);
```
Comment (lucferbux) [inline backend/src/routes/api/namespaces/namespaceUtils.ts:49]: And same here, should we log here the error? 
Logging failed attempts to update a resource could be useful if we need to debug security issues.

**Review by lucferbux — CHANGES_REQUESTED** [review]

File: backend/src/routes/api/k8s/pass-through.ts [hunk 3]
```diff
@@ -74,7 +80,7 @@ export const passThrough = (
               data += chunk;
             })
             .on('end', () => {
-              let parsedData: K8sResourceCommon | K8sStatus;
+              let parsedData;
```
[the remark this answers is not in the document]
Comment (lucferbux) [reply backend/src/routes/api/k8s/pass-through.ts:83]: To be more clear, I'm not against this, I was just thinking out loud.

File: backend/src/routes/api/namespaces/namespaceUtils.ts [hunk 4]
```diff
@@ -16,6 +18,36 @@ export const applyNamespaceChange = (
...
+        apiVersion: 'authorization.k8s.io/v1',
+        kind: 'SelfSubjectAccessReview',
+        spec: {
+          resourceAttributes: {
+            group: 'project.openshift.io',
+            resource: 'projects',
+            subresource: '',
+            verb: 'update',
+            name,
+            namespace: name,
```
Comment (andrewballantyne) [inline backend/src/routes/api/namespaces/namespaceUtils.ts:40]: Do you need to pass namespace 🤔

File: backend/src/routes/api/namespaces/namespaceUtils.ts [hunk 5]
```diff
@@ -16,6 +18,36 @@ export const applyNamespaceChange = (
...
+  const kc = fastify.kube.config;
+  const cluster = kc.getCurrentCluster();
+
+  const selfSubjectAccessReviewResult = await passThrough<V1SelfSubjectAccessReview>(
+    fastify,
+    request,
+    {
+      url: `${cluster.server}/apis/authorization.k8s.io/v1/selfsubjectaccessreviews`,
+      method: 'POST',
+      requestData: JSON.stringify({
```
Comment (andrewballantyne) [inline backend/src/routes/api/namespaces/namespaceUtils.ts:30]: I'm a little disappointed this object is not typed.

Can you make this whole call a new function, provide a type to the data you are giving to `requestData`. 

It'll help with keeping this specific block of code out of the namespaceUtils directly, giving us a more declarative approach to this code?

File: backend/src/routes/api/k8s/pass-through.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (andrewballantyne) [reply backend/src/routes/api/k8s/pass-through.ts:83]:
```suggestion
              let parsedData: T | K8sStatus;
```
Is this not possible?

**Review by andrewballantyne — CHANGES_REQUESTED** [review]

File: backend/src/routes/api/namespaces/namespaceUtils.ts (hunk 4 above)
Comment (DaoDaoNoCode) [reply backend/src/routes/api/namespaces/namespaceUtils.ts:40]: Yes, I think so. I tried to remove the namespace and the functionality doesn't work any more, check the comment here https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/src/app/components/utils/rbac.tsx#L48-L49

File: backend/src/routes/api/namespaces/namespaceUtils.ts (hunk 1 above)
Comment (DaoDaoNoCode) [reply backend/src/routes/api/namespaces/namespaceUtils.ts:24]: I think the pass-through function will log all the errors, so I don't make any other process here.

File: backend/src/routes/api/namespaces/namespaceUtils.ts (hunk 2 above)
Comment (DaoDaoNoCode) [reply backend/src/routes/api/namespaces/namespaceUtils.ts:49]: Good suggestion, added a log here.

File: backend/src/routes/api/namespaces/namespaceUtils.ts (hunk 4 above)
Comment (andrewballantyne) [reply backend/src/routes/api/namespaces/namespaceUtils.ts]: Good catch! Thanks

File: backend/src/routes/api/k8s/pass-through.ts [hunk 6]
```diff
@@ -33,26 +53,22 @@ const setupRequest = async (
     safeURL = queryParams.join('?');
   }
 
-  const requestOptions = await getDirectCallOptions(fastify, request, url);
-
-  return {
+  const updatedData = {
```
Comment (andrewballantyne) [inline backend/src/routes/api/k8s/pass-through.ts:56]:
```suggestion
  const updatedData: PassThroughData = {
```

**Review by andrewballantyne — APPROVED** [review]
We need to look at our linter again -- seems just omitting types is still allowed.

File: backend/src/routes/api/k8s/pass-through.ts (hunk 6 above)
Comment (DaoDaoNoCode) [reply backend/src/routes/api/k8s/pass-through.ts:56]: @andrewballantyne This is the backend lint settings which we didn't change and agreed it doesn't worth the effort to change for now because we will refactor it one day.

Comment (andrewballantyne) [reply backend/src/routes/api/k8s/pass-through.ts:56]: Pass through API is not going anywhere -- this won't just be removed some day, this was a gap. But the way TS infers types, it should not cause an issue.
