### PR TITLE
Make notebook controller access button to link behavior

### LINKED ISSUE #1591: [Bug]: access notebook server button should behave like a link
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

The `Access notebook server` button on the `Notebook server control panel` page doesn't give direct access to the server URL for the user to be able to copy it or open the link in a new browser tab. The button isn't rendered as a link in the page but rather an action.

image

### Expected Behavior

Expect all actions that perform navigation to be rendered as links to take advantage of build in browser behavior and accessibility.

### Steps To Reproduce

1. Create a notebook server
2. navigate to the notebook control panel page `/notebookController`
3. ctrl+click on the `Access notebook server` button
4. Expected: a new window / tab to open
5. Observed: content is loaded in the current tab
6. Similarly, right click and attempt to "copy link address"
7. Observed: no option to copy link address since the button has no href.

### Workaround (if any)

1. Duplicate the tab
2. Click the `access notebook server` button

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1591 

## Description

Didn't make any visual changes here, only updated the button's behavior to make it a link.

## How Has This Been Tested?

1. Go to notebook controller page (Jupyter card on Enabled page), spawner a notebook
2. After spawning, don't get into the notebook, you will see the control panel
3. Click on the `Access notebook server` button, you will be navigated to the notebook in the same tab
4. `Cmd/Ctrl` + Click on the button, you will be able to access the notebook in a new tab
5. Right click the button, you will see some link options like `Copy link address` or `Open link in new tab`

## Test Impact

N/A, just behavior change.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: frontend/src/pages/notebookController/screens/server/NotebookServer.tsx [hunk 1]
```diff
@@ -55,17 +57,15 @@ export const NotebookServer: React.FC = () => {
               <ActionList>
                 <ActionListItem
                   onClick={() => {
-                    if (notebook.metadata.annotations?.['opendatahub.io/link']) {
-                      window.location.href = notebook.metadata.annotations['opendatahub.io/link'];
-                    } else {
+                    if (link === '#') {
```
Comment (christianvogt) [inline frontend/src/pages/notebookController/screens/server/NotebookServer.tsx:60]: I suggest you call `preventDefault()` if the link is invalid to prevent the user from ctrl clicking the link etc...
```suggestion
                    if (link === '#') {
                      e.preventDefault();
```

**Review by andrewballantyne — APPROVED** [review]
