### PR TITLE
Gracefully handle image packages and software JSON parse error

### LINKED ISSUE #1493: [Bug]: Dependency Annotations can blindly crash
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Directly installing the Dashboard at the latest (eg. `odh-dashboard/main`)

### Version

v2.12.0

### Current Behavior

When you have a custom image stream tag that has invalid JSON in one of these annotations:
- `'opendatahub.io/notebook-software'`
- `'opendatahub.io/notebook-python-dependencies'`

We crash the thread on the server with an uncaught JSON parse error.

This results in an unpleasant and confusing error that locks up the Jupyter tile: 
image

### Expected Behavior

1. We shouldn't crash the thread or lock up the UI element
2. We should gracefully handle the error (removing content or presenting some error for the failed JSON blob)
3. This should work for both Jupyter Tile and the DS Projects view (which was reported not to have the breaking error)

### Steps To Reproduce

1. Create an image stream tag that has invalid JSON data in one of the annotations
2. View the Jupyter Tile

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Close #1493 

## Description

After a discussion with the UX, we decide to parse the error dependency string as empty, which means when the parse error happens, the backend will return an empty array to the frontend side. So from the user's perspective, it can still normally use the image but see no dependencies in the image.

## How Has This Been Tested?

1. Go to the cluster, and find one image stream that the notebook controller spawner page could fetch
2. Change the `annotation['opendatahub.io/notebook-python-dependencies']` of its tag to an invalid string which could cause the JSON parse error
3. Go to the notebook controller spawner page in the dashboard, see if you could successfully load the page and select the image
4. Check the details of the image by clicking the tooltip next to it, and find if the packages are not visible in the details

## Test Impact

N/A, it's just a parse error solved at the backend side

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

File: backend/src/routes/api/images/imageUtils.ts [hunk 1]
```diff
@@ -194,16 +194,10 @@ const mapImageStreamToBYONImage = (is: ImageStream): BYONImage => ({
...
-    ) as BYONImagePackage[]),
-  software:
-    is.spec.tags &&
-    (JSON.parse(
-      is.spec.tags[0].annotations['opendatahub.io/notebook-software'],
-    ) as BYONImagePackage[]),
+  packages: jsonParsePackage(
+    is.spec.tags?.[0]?.annotations['opendatahub.io/notebook-python-dependencies'],
+  ),
+  software: jsonParsePackage(is.spec.tags?.[0]?.annotations['opendatahub.io/notebook-software']),
```
Comment (andrewballantyne) [inline backend/src/routes/api/images/imageUtils.ts:200]: Do we not want to conditionally check to see if `annotations` is there?

Comment (Gkrumbach07) [reply backend/src/routes/api/images/imageUtils.ts:200]: It might not really matter if undefined is being passed in anyways. 

`JSON.parse(undefined)` and `JSON.parse("invalid json")` both would be caught by the function and properly returned as an empty array

Comment (DaoDaoNoCode) [reply backend/src/routes/api/images/imageUtils.ts:200]: I think Andrew worries about the possible type error that could crush the backend. I can update it to `is.spec.tags?.[0]?.annotations?.['opendatahub.io/notebook-software']`

Comment (DaoDaoNoCode) [reply backend/src/routes/api/images/imageUtils.ts:200]: Actually, that hardly happens unless someone directly changes the YAML file of the image stream.

Comment (Gkrumbach07) [reply backend/src/routes/api/images/imageUtils.ts]: why does this not produce a type error now? if the annotation can be undefined

```
  annotations?: { [key: string]: string };
```

and the function expects a non undefined string? Am i missing something

Comment (DaoDaoNoCode) [reply backend/src/routes/api/images/imageUtils.ts]: Ohhhhh, yes, you are right... I already updated it, anyway. it will be refactored in the BYON phase 2

Comment (lucferbux) [reply backend/src/routes/api/images/imageUtils.ts]: ohhh right, good catch, kinda weird that didn't raise an error since the annotation was optional, first read I swear I thought it was optionally chained.

**Review by lucferbux — APPROVED** [review]
/lgtm
