### PR TITLE
fix: adds service mesh annotations on ns creation

### LINKED ISSUE #2095: [Bug]: Regression in service mesh annotation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

2.4 (incubation)

### Current Behavior

We are applywing the `opendatahub.io/service-mesh` when enabling modelmesh rather than just when creating the project.

### Expected Behavior

That annotation should be added on project creation

### Steps To Reproduce

1. Create a new project
2. Check that the `opendatahub.io/service-mesh` is missing

### Workaround (if any)

Add the annotation manually

### What browsers are you seeing the problem on?

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by bartoszmajsak**
## Description
This functionality has been accidentally moved to `MODEL_MESH_PROMOTION` case, breaking service mesh support in newly created data science projects.

## How Has This Been Tested?

Closes #2095 

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: backend/src/routes/api/namespaces/namespaceUtils.ts [hunk 1]
```diff
@@ -73,14 +73,14 @@ export const applyNamespaceChange = async (
       labels = {
         'opendatahub.io/dashboard': 'true',
       };
+      annotations = {
```
Comment (lucferbux) [inline backend/src/routes/api/namespaces/namespaceUtils.ts:76]: Great, this is interesting, it might have happened when merging both the [f/ossm](https://github.com/opendatahub-io/odh-dashboard/tree/f/ossm) and [f/model-serving](https://github.com/opendatahub-io/odh-dashboard/tree/f/model-serving) into incubation, good catch.

This is a weird situation, but I think solving this in `incubation` is the right approach, we need to be careful once we promote ossm to main again @andrewballantyne 


@bartoszmajsak just fix the linting issue and we can merge it.

**Review by lucferbux — CHANGES_REQUESTED** [review]

File: backend/src/routes/api/namespaces/namespaceUtils.ts (hunk 1 above)
Comment (bartoszmajsak) [reply backend/src/routes/api/namespaces/namespaceUtils.ts:76]: The diff / git annotations aren't helping find which commit brought this. It might be because of the complex nature of how you deal with changes now/your branching strategy. I agree it could have been an auto-merge that went wrong. I managed to pin it to this merge commit: https://github.com/opendatahub-io/odh-dashboard/commit/39956df0dc734b1ba9f5f9b0472d19cc2f54683e#diff-a319cea33b543d7642d6cdd32ffea3771e0fdafb54fe1cfedd4a7d3ebc8930d0

As for the linter - it was a bit confusing at first, but it's fixed in ed8e8943 :)

**Review by lucferbux — APPROVED** [review]
/lgtm
