### PR TITLE
Ignore 409 case for RBs

### LINKED ISSUE #478: [Bug]: Concurrent Users - First Login; 409 Conflict
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During testing, QE ran multiple concurrent users against the Dashboard. In a few situations, two users would visit the KFNBC page at the same time before we have validated the `notebookNamespace`. 

Both users get back a state of the RoleBinding for the namespace and it would be not created at this time. So both users request to create. First one is successful, the second one hits a 409 conflict. The second user now gets an error screen.

### Expected Behavior

Let the create not break the API if it is a 409 status code. Conflicts here are not a problem, it's a deterministic RoleBinding shape, so it does not matter if there is already one on cluster, it will be 1:1 with what you're trying to create.

### Steps To Reproduce

Testing this will be weird... Best case I can think of maybe is to have two browser windows side by side and refresh both after deleting the RoleBinding behind the `notebookNamespace`.

You may get better success by going into your DevTools Network Tab and turning on the network throttling.

Actual steps are:
1. Setup the `notebookNamespace` in your OdhDashboardConfig
1. Go the KFNBC with two users at the same time -- for the first time / when there is no RoleBinding

### Workaround (if any)

Access the namespace once by yourself before allowing multiple concurrent users to try to access it.

### OpenShift Infrastructure Version

_No response_

### Openshift Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
2.1
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by maroroman**
Resolves #478 

## Description
Adds a case for 409 status code, ignoring the failure.

This solves cases where 2 POST requests are sent to the cluster at the same time causing a conflict for RBs

## How Has This Been Tested?

This one was fun to test

1. Deploy odh-dashboard with current changes
2. Create two browser windows each with the Notebook Spawner
3. Delete whichever image puller RB is used (`opendatahub-image-pullers` in my case)
4. Refresh both windows in quick succession. (I also recommend the F12 debug screen to check success)
5. If network logs show that both windows had a 404 occur (and a POST afterwards) check the pod logs.
6. Expect similar output: 
image

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: backend/src/routes/api/rolebindings/index.ts [hunk 1]
```diff
@@ -41,8 +41,13 @@ module.exports = async (fastify: KubeFastifyInstance) => {
...
         return rbResponse.body;
       } catch (e) {
-        fastify.log.error(`rolebinding could not be created: ${e}`);
-        reply.send(e);
+        if (e.response?.statusCode === 409) {
+          fastify.log.warn(`Rolebinding already present, skipping creation.`);
+          return {};
+        } else {
+          fastify.log.error(`rolebinding could not be created: ${e}`);
+          reply.send(e);
```
Comment (andrewballantyne) [inline backend/src/routes/api/rolebindings/index.ts:49]: Can we look to log `e.response.body.message` instead of just `e`... also could we create a new Error object and send that instead? We do too many logging of just `e` or `e.toString()` and it serializes poorly into the logs. 

When a request fails through the kube library, there is a status object at `e.response.body` -- this is the K8s response to the request. `.message` on that gives back what k8s saw happen.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]

File: backend/src/routes/api/rolebindings/index.ts (hunk 1 above)
Comment (maroroman) [reply backend/src/routes/api/rolebindings/index.ts]: Ok changed it to new error object and message

**Review by andrewballantyne — APPROVED** [review]
Works like a charm.

Tested it by doing the following:
1. Have two browsers logged in with two users (I used Incognito on server & localhost for the PR)
2. Put a breakpoint in both codes at the moment of an API request to validate namespaces with a rolebinding
3. Deleted the existing rolebinding (because I needed to get the breakpoints in there, I had to run it once due to code splitting)
4. Run until the breakpoint hits both
5. Throttle the network traffic down so the get call is slower

Then two scenarios were executed:

Scenario A: Validate Bug
- Localhost with this fix was run first
- Incognito with an older dashboard (without the fix) was run second

Result: Error was visible in my incognito window - 409 conflict

Scenario B: Validate Fix
- Incognito with an older dashboard (without the fix) was run first
- Localhost with this fix was run second

Result: no 409 issues in either browser and both saw their respective pages on the other end.
Both network calls were 200 success & no conflict was reported to the client.
