### PR TITLE
Set KFNBC as default

### LINKED ISSUE #442: [Bug]: Fix it so KFNBC is on by default
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In ODH 2.1 release we are looking to have KFNBC always on by default. If we want this, we should update it so our backend does that when there is a lack of config in place. We should not override their existing settings if they want it off, but we should not default to showing JH anymore.

### Expected Behavior

_No response_

### Steps To Reproduce

Scenarios to test with the OdhDashboardConfig in the following states:

- With no config
- With a config and `notebookController` missing from the config
- With a config and `notebookController.enabled` set to `false`
- And naturally it shouldn't have any problems with `notebookController.enabled` set to `true`

The UI steps are just to view the home page (Enabled components) and see the `Juypter` tile instead of the `JuypterHub` tile

### Workaround (if any)

_No response_

### OpenShift Infrastructure Version

_No response_

### Openshift Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
2.1
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
## Description

Closes #442 
Set Jupyter tile as default.
As for notebook sizes, try to fetch them from the dashboard config, if there are no `notebookSizes` in the dashboard config, we create some default sizes for the users in the code.
Refactor the way to fetch dashboard config, App.tsx will be the only place to make the API call to get dashboard config, and all the other components use context to get it. If there is something wrong when fetching the dashboard config, we show an error page.

## How Has This Been Tested?

Try to remove `notebookController` field from the dashboard config. It will still show Jupyter tile now. The JupyterHub tile will only be enabled when the following config is applied: 
```
notebookController:
  enabled: false
```

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: frontend/src/app/AppContext.ts [hunk 1]
```diff
@@ -1,23 +1,22 @@
...
   buildStatuses: [],
-  dashboardConfig: blankDashboardCR,
+  dashboardConfig: null,
 };
 
-const AppContext = React.createContext(defaultAppContext);
+export const AppContext = React.createContext(defaultAppContext);
 
-export default AppContext;
+export const useAppContext = (): AppContextProps => React.useContext(AppContext);
```
Comment (andrewballantyne) [inline frontend/src/app/AppContext.ts:22]: What are you saving here by creating this?

File: frontend/src/app/AppLauncher.tsx [hunk 2]
```diff
@@ -90,9 +89,7 @@ const AppLauncher: React.FC<AppLauncherProps> = ({ dashboardConfig }) => {
 
     const getODHApplications = (): Section[] => {
       const osConsoleAction = getOpenShiftConsoleAction();
-      const ocmAction = dashboardConfig.disableClusterManager
-        ? null
-        : getOCMAction(clusterID, clusterBranding);
+      const ocmAction = disableClusterManager ? null : getOCMAction(clusterID, clusterBranding);
```
Comment (andrewballantyne) [inline frontend/src/app/AppLauncher.tsx:92]: Noice, love to see less dependencies on the hook 👍

File: frontend/src/pages/notebookController/screens/server/usePreferredNotebookSize.ts [hunk 3]
```diff
@@ -1,29 +1,33 @@
...
-      }
+  if (currentUserState.lastSelectedSize) {
+    const size = sizes.find(
+      (notebookSize) => notebookSize.name === currentUserState.lastSelectedSize,
+    );
+    if (size) {
+      defaultSize = size.name;
     } else {
-      defaultSize = dashboardConfig.spec.notebookSizes[0].name;
+      defaultSize = sizes[0].name;
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/usePreferredNotebookSize.ts:24]: Can we also log something into the console here? I feel like we should just note that something funky happened trying to get it. That way if a report comes in we can ask for the console and just say "ah yeah, your default somehow was removed / renamed" rather than just try to reproduce it.

File: frontend/src/services/notebookService.ts [hunk 4]
```diff
@@ -15,7 +15,7 @@ import {
 import { RecursivePartial } from '../typeHelpers';
 import { LIMIT_NOTEBOOK_IMAGE_GPU } from '../utilities/const';
 import { MOUNT_PATH } from '../pages/notebookController/const';
-import { usernameTranslate } from 'utilities/notebookControllerUtils';
+import { usernameTranslate } from '../utilities/notebookControllerUtils';
```
Comment (andrewballantyne) [inline frontend/src/services/notebookService.ts:18]: 🤔 I wonder if we should look to have more paths, not less... save us from `..` hell. Maybe not for your PR though. Food for thought.

File: frontend/src/utilities/useWatchDashboardConfig.tsx [hunk 5]
```diff
@@ -4,39 +4,14 @@ import { POLL_INTERVAL } from './const';
...
-      disableUserManagement: false,
-    },
-    groupsConfig: {
-      adminGroups: 'odh-admins',
-      allowedGroups: 'system:authenticated',
-    },
-  },
-};
-
 export const useWatchDashboardConfig = (): {
```
Comment (andrewballantyne) [inline frontend/src/utilities/useWatchDashboardConfig.tsx:7]: We should probably move this utility to the `App` folder right? Maybe even call it something like `useApplicationSettings` or something when we move it. That way no one will get wise and try to import it elsewhere. We want to favour people into using the app context one, so if we rename it might make it even less palpable.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]

File: frontend/src/app/AppContext.ts (hunk 1 above)
Comment (andrewballantyne) [reply frontend/src/app/AppContext.ts:22]: Talk with Juntao -- Recommended we do not do this in the future, I see no gain in this effort and it touches a lot of spots. But it is fine, we can leave it for ease of use.

File: frontend/src/pages/notebookController/screens/server/usePreferredNotebookSize.ts [hunk 6]
```diff
@@ -1,29 +1,52 @@
...
-] => {
-  const { dashboardConfig } = React.useContext(AppContext);
+export const usePreferredNotebookSize = (): {
+  selectedSize: NotebookSize;
+  setSelectedSize: (size: string) => void;
+  sizes: NotebookSize[];
+} => {
+  const { dashboardConfig } = useAppContext();
+  const notification = useNotification();
+  const sizes = dashboardConfig?.spec?.notebookSizes || DEFAULT_NOTEBOOK_SIZES;
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/usePreferredNotebookSize.ts:15]: An empty array is truthy -- you crash the UI with no notebooks -- lets call no notebookSizes the same as not being defined.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
Looking good, but I ran into an issue with a wonky config.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
Hmm, got a couple other weird things too... mid spinning up my Notebook I changed my notebookSizes -- it gave me a white screen, too many re-renders.

```
Warning: Cannot update a component (`App`) while rendering a different component (`Unknown`). To locate the bad setState() call inside `Unknown`, follow the stack trace as described in https://fb.me/setstate-in-render
    in Unknown (created by NotebookServerRoutes)
    in Route (created by NotebookServerRoutes)
    in Switch (created by NotebookServerRoutes)
    in NotebookServerRoutes (created by NotebookControllerTabs)
    in section (created by Context.Consumer)
    in TabContentBase (created by ForwardRef)
    in ForwardRef (created by Tabs)
    in Tabs (created by NotebookControllerTabs)
    in div (created by NotebookControllerTabs)
    in NotebookControllerTabs (created by NotebookController)

```
Also got this -- when I refreshed I got it again.

I also got two notifications 🤔 I suspect this is because we do it in the base of the hook, rather than an effect.
Screen Shot 2022-08-31 at 3 22 38 PM

File: backend/src/utils/resourceUtils.ts [hunk 7]
```diff
@@ -362,7 +362,12 @@ const fetchConsoleLinks = async (fastify: KubeFastifyInstance) => {
 };
 
 export const initializeWatchedResources = (fastify: KubeFastifyInstance): void => {
-  dashboardConfigWatcher = new ResourceWatcher<DashboardConfig>(fastify, fetchDashboardCR);
+  dashboardConfigWatcher = new ResourceWatcher<DashboardConfig>(
+    fastify,
+    fetchDashboardCR,
+    undefined,
+    2000,
```
Comment (andrewballantyne) [inline backend/src/utils/resourceUtils.ts:369]: undo?

File: frontend/src/app/AppContext.ts [hunk 8]
```diff
@@ -15,9 +14,14 @@ const defaultAppContext: AppContextProps = {
   setIsNavOpen: () => undefined,
   onNavToggle: () => undefined,
   buildStatuses: [],
-  dashboardConfig: blankDashboardCR,
+  /* DO NOT DO THIS!!!!!!!!!!! :( */
+  // dashboardConfig will never be null during runtime
+  // tests will just mock this
+  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+  // @ts-ignore
+  dashboardConfig: null,
```
Comment (andrewballantyne) [inline frontend/src/app/AppContext.ts:22]: Can you try one other things -- talked to another dev and he said maybe `as DashboardConfig` might work. Just trying to set the `null` around TS is all we need to do.

File: frontend/src/app/TelemetrySetup.tsx [hunk 9]
```diff
@@ -0,0 +1,12 @@
+import * as React from 'react';
+import { useSegmentTracking } from '../utilities/useSegmentTracking';
+import { useTrackHistory } from '../utilities/useTrackHistory';
+
+const TelemetrySetup: React.FC = () => {
```
Comment (andrewballantyne) [inline frontend/src/app/TelemetrySetup.tsx:5]: Is this used anywhere? I thought we added it to `App` 🤔

File: frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx [hunk 10]
```diff
@@ -1,55 +1,60 @@
...
       const name = size.name;
       const desc =
-        `Limits: ${size?.resources?.limits?.cpu || '??'} CPU, ` +
-        `${size?.resources?.limits?.memory || '??'} Memory ` +
-        `Requests: ${size?.resources?.requests?.cpu || '??'} CPU, ` +
-        `${size?.resources?.requests?.memory || '??'} Memory`;
+        `Limits: ${size.resources?.limits?.cpu || '??'} CPU, ` +
+        `${size.resources?.limits?.memory || '??'} Memory ` +
+        `Requests: ${size.resources?.requests?.cpu || '??'} CPU, ` +
+        `${size.resources?.requests?.memory || '??'} Memory`;
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx:27]: FWIW, `resources` is a required field -- everything in it is optional.

File: frontend/src/utilities/useNotification.ts [hunk 11]
```diff
@@ -39,7 +44,38 @@ const useNotification = (): NotificationFunc => {
     [dispatch],
   );
 
-  const notification = React.useMemo(() => ({ success, error }), [success, error]);
+  const info: NotificationProps = React.useCallback(
+    (title, message?) => {
+      dispatch(
+        addNotification({
+          status: 'info',
```
Comment (andrewballantyne) [inline frontend/src/utilities/useNotification.ts:51]: Use your enum for the `status`... Update all 4

**Review by andrewballantyne — CHANGES_REQUESTED** [review]

File: frontend/src/utilities/useNotification.ts (hunk 11 above)
Comment (andrewballantyne) [reply frontend/src/utilities/useNotification.ts:51]: nvm -- retracting this comment.

**Review by andrewballantyne — COMMENTED** [review]
Code looking good -- will test it out once I get a moment. Trying to find more edge cases.

**Review by andrewballantyne — APPROVED** [review]
Looking good to me. Thanks for the refactor and the work to setup the appropriate `notebookSizes`.
