### PR TITLE
Open new tab for new spawned notebook server

### LINKED ISSUE #526: [Bug]: Make KFNBC Launch Notebook In New Tab
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we spawn a notebook for JH it was fine to consume the tab in that effort -- it was already a new tab when our dashboard linked out.

However when we spawn through KFNBC, we shouldn't override our current page with a new application -- makes it hard to return. 

### Expected Behavior

On Start Modal finish (and the access server button) open a new tab to JL... do not consume our Dashboard tab with any external application.

### Steps To Reproduce

Spawn a notebook or revisit a spawned notebook

### Workaround (if any)

_No response_

### OpenShift Infrastructure Version

_No response_

### Openshift Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
2.1
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
## Description

Closes #526 
~The new tab will be blocked by the browser currently because it's not triggered by a user action, we need to wait until @andrewballantyne chats with the UX to see if we get some better ideas.~

Create a new field that controls whether the user wants to open the notebook in a new or current tab. If he wants the current tab, it keeps the same behavior. If the user wants to open it in a new tab, the page will not automatically redirect after successfully spawning the notebook. It will instead show 2 buttons for the user to choose his next step.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by andrewballantyne** [comment]
Waiting on feedback from the RHODS comment https://issues.redhat.com/browse/RHODS-5187 -- UX and I came up with some functionality we can do to make this happen, but we need to verify this new functionality works with the reporter -- otherwise we may end up tossing this out.

File: frontend/src/pages/notebookController/screens/server/BrowserTabPreferenceCheckbox.tsx [hunk 1]
```diff
@@ -0,0 +1,30 @@
+import * as React from 'react';
+import { Checkbox, FormGroup } from '@patternfly/react-core';
+
+type BrowserTabPreferenceCheckboxProps = {
+  isChecked: boolean;
+  setChecked: (checked: string) => void;
+};
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/BrowserTabPreferenceCheckbox.tsx:7]: Maybe this component is unique -- it doesn't need to interact with the form -- we should probably just include all state about it including where it is pulling from inside this component.

File: frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx [hunk 2]
```diff
@@ -85,6 +93,12 @@ const SpawnerPage: React.FC = () => {
   const [variableRows, setVariableRows] = React.useState<VariableRow[]>([]);
   const [createInProgress, setCreateInProgress] = React.useState<boolean>(false);
   const [submitError, setSubmitError] = React.useState<Error | null>(null);
+  const [isUsingCurrentTabFromStorage, setUsingCurrentTab] = useLocalStorage(
+    CURRENT_BROWSER_TAB_PREFERENCE,
+  );
+  const isUsingCurrentTab = isUsingCurrentTabFromStorage
+    ? JSON.parse(isUsingCurrentTabFromStorage)
+    : false;
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx:101]: Move items into the component as per last comment. Also make this a hook by itself so you can use it in two spots.

File: frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx [hunk 3]
```diff
@@ -417,6 +435,7 @@ const SpawnerPage: React.FC = () => {
             }
             setCreateInProgress(false);
           }}
+          isUsingCurrentTab={isUsingCurrentTab}
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx:438]: We could pull this state from localStorage in the modal just to avoid passing it around. This state isn't exactly "form state" as it is application state.

File: frontend/src/pages/notebookController/screens/server/StartServerModal.tsx [hunk 4]
```diff
@@ -53,32 +63,46 @@ const StartServerModal: React.FC<StartServerModalProps> = ({ open, spawnInProgre
...
     spawnStatus?.status === AlertVariant.danger || spawnStatus?.status === AlertVariant.warning;
 
+  const navigateToNotebook = React.useCallback(
+    (useCurrentTab: boolean): void => {
+      if (notebookLink) {
+        if (useCurrentTab) {
+          window.location.href = notebookLink;
+        } else {
+          window.open(notebookLink, '_blank');
+          history.push('/notebookController');
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/StartServerModal.tsx:73]: Do we need this? 🤔 This is because they can just close the modal?

**Review by andrewballantyne — CHANGES_REQUESTED** [review]

File: frontend/src/pages/notebookController/screens/server/StartServerModal.tsx (hunk 4 above)
Comment (DaoDaoNoCode) [reply frontend/src/pages/notebookController/screens/server/StartServerModal.tsx:73]: I can remove this force redirect, but I may need to change the logic to set `showClose` of the Modal. Currently, we only show the close icon when the spawning fails, that's how they did in JH, so there is no way for the users to close the modal if the spawning succeeds. We can definitely change that to show the close icon on both success (without setting spawn in the current tab) and failed status. WDYT?

Comment (andrewballantyne) [reply frontend/src/pages/notebookController/screens/server/StartServerModal.tsx:73]: No definitely don't show additional buttons unless we need to, it doesn't need to be a nosy modal of buttons. But why did you add it in the first place? Am I missing the use case here -- don't we just stop the redirect while the page is going or was that logic removed somewhere? 🤔

Comment (DaoDaoNoCode) [reply frontend/src/pages/notebookController/screens/server/StartServerModal.tsx:73]: Let's think of the scenarios. First, on the spawner page, the user doesn't check `Start server in current tab`, then he starts a notebook, when the spawning success, we will show the modal, and there are 2 buttons for the user to choose whether to open a new tab for the notebook or launch the notebook in the current tab. What if he chooses to launch the notebook in a new tab? Then there will be a new tab for the notebook opens, but the old tab is still there, when he switches back to the old tab (dashboard one), he can still see this starting server modal and cannot even find a button to close it. I am doing this because when the user makes the choice to open the notebook whether in a new tab or a current tab, I should help him to navigate to the controller page for the dashboard old tab, but not stay watching the un-closable modal.

Comment (andrewballantyne) [reply frontend/src/pages/notebookController/screens/server/StartServerModal.tsx:69]: Wow, yes -- of course. These were comments made by me without having fired up your PR. Absolutely correct, thanks for the clarification.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]

File: frontend/src/pages/notebookController/screens/server/useBrowserTabPreference.ts [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+  } catch (e) {
+    console.error('Error parsing user current tab preference from local storage', e);
+    isUsingCurrentTab = false;
+  }
+
+  const setUsingCurrentTab = React.useCallback(
+    (using: boolean) => {
+      let parsedUsing: string;
+      try {
+        parsedUsing = JSON.stringify(using);
```
[the remark this answers is not in the document]
Comment (DaoDaoNoCode) [reply frontend/src/pages/notebookController/screens/server/useBrowserTabPreference.ts:27]: I think this situation won't happen in this case, I can remove the try-catch block for stringify.

**Comment by DaoDaoNoCode** [comment]
Conflicts solved.

**Review by andrewballantyne — APPROVED** [review]
LGTM

There is a brief moment when it is redirecting that you can click both buttons or spam the url redirect button -- but I see no real problem there. They can't do anything else.
