### PR TITLE
use generic object state on data connections and prevent resetting on edit

### LINKED ISSUE #1487: [Bug]: Workbench spawner form "resets" data connections on edit
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Directly installing the Dashboard at the latest (eg. `odh-dashboard/main`)

### Version

v2.12.0

### Current Behavior

When you edit a workbench that has a data connection assigned to it already, and you select _Create a new data connection_, it will reset back to the  _Use Existing_ option

### Expected Behavior

The data connection should not reset after changes were made

### Steps To Reproduce

1. create a workbench with a data connection
2. stop workbench and edit
3. select "Create a new data connection" in the data connection section
4. wait...
5. it should reset back to what it was originally

### Workaround (if any)

submit before it resets or re-input data connection values

### What browsers are you seeing the problem on?

Chrome

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1487 

## Description

Refactor the data connection object to the generic state object. Also, fixed the problem mentioned in the issue. It's because we have an unstable reference that will trigger the `useEffect` hook in `useNotebookDataConnection` every time the data connections are fetched. Instead of passing the array to the `useEffect` hook, we take the value we want outside of it and pass that stable value to the hook could fix this problem.

## How Has This Been Tested?

1. Create a workbench with data connection
2. Stop the workbench
3. Edit the workbench
4. Go to the data connection section, change it to create a new data connection
5. Make sure the choice will not be reset back to use existing data connection

## Test Impact

N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts [hunk 1]
```diff
@@ -15,36 +20,33 @@ export const getNotebookDataConnection = (
...
   dataConnection: DataConnectionData,
-  setDataConnection: (connection: DataConnectionData) => void,
+  setDataConnection: UpdateObjectAtPropAndValue<DataConnectionData>,
+  resetDefaults: () => void,
 ] => {
-  const [dataConnection, setDataConnection] = React.useState<DataConnectionData>({
+  const createDataState = useGenericObjectState<DataConnectionData>({
     type: 'creating',
     enabled: false,
   });
```
Comment (christianvogt) [inline frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts:33]: Would it not make sense to set the default values and then remove the `useEffect` ?

```suggestion
  const notebookDataConnectionSecret = getNotebookDataConnection(notebook, dataConnections)?.data
    .metadata.name;
  const createDataState = useGenericObjectState<DataConnectionData>(
    notebookDataConnectionSecret
      ? {
          type: 'existing',
          enabled: true,
          existing: {
            secretRef: {
              name: notebookDataConnectionSecret,
            },
          },
        }
      : {
          type: 'creating',
          enabled: false,
        },
  );
```

File: frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts [hunk 2]
```diff
@@ -15,36 +20,33 @@ export const getNotebookDataConnection = (
...
+      setCreateData('type', 'existing');
+      setCreateData('enabled', true);
+      setCreateData('existing', {
+        secretRef: {
+          name: notebookDataConnectionSecret,
+        },
+      });
     }
-  }, [notebook, dataConnections]);
+  }, [notebook, setCreateData, notebookDataConnectionSecret]);
```
Comment (christianvogt) [inline frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts:49]: It's odd that once the default form data has been established, that we may still reset the values on the user in this `useEffect`. See previous comment as to whether or not we can remove this.

File: frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts (hunk 1 above)
Comment (DaoDaoNoCode) [reply frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts:33]: Wow, you are correct, didn't know why I used that way before...

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm

tested before and after and your fix corrects the reset and it looks like you fixed @christianvogt's comments
