### PR TITLE
Parse BYON repository URL correctly

### LINKED ISSUE #1085: [Bug]: Custom notebook image fails to pull with registry port
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a custom notebook image hosted in the OCP internal registry, any attempt to spin up a session using this notebook causes imagePullBackoff. Basic troubleshooting points to parsing of the image name. It looks like anytime there is a ":<portnumber>" descriptor in the name, it gets parsed incorrectly. When there is no port number, like quay.io, it parses correctly.

### Expected Behavior

The custom image should spin up without errors regardless of the existence of port number in the name.

### Steps To Reproduce

1. Create a custom notebook image stored in the internal registry. (image stream)
2. Add this image to the custom notebooks in your ODH environment.
3. Launch a notebook with this new image.

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  creationTimestamp: '2023-03-26T12:29:23Z'
  finalizers:
    - kfdef-finalizer.kfdef.apps.kubeflow.org
  generation: 2
  managedFields:
    - apiVersion: kfdef.apps.kubeflow.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:applications': {}
          'f:repos': {}
      manager: Mozilla
      operation: Update
      time: '2023-03-26T12:29:23Z'
    - apiVersion: kfdef.apps.kubeflow.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"kfdef-finalizer.kfdef.apps.kubeflow.org"': {}
        'f:status': {}
      manager: opendatahub-operator
      operation: Update
      time: '2023-03-26T12:29:23Z'
  name: opendatahub
  namespace: odh
  resourceVersion: '92958'
  uid: d9c111c7-e20d-4695-8a15-dd012ccc97e1
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-notebook-controller
      name: odh-notebook-controller
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: notebook-images
      name: notebook-images
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.4.2'
status: {}
```

### Anything else

Originally entered in doc repo
https://github.com/opendatahub-io/opendatahub.io/issues/76

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1085 

## Description

The PR did the following things:
1. Use regex to match the repository URL, which could help correctly parse the hostname and the tag name
2. If the user doesn't input the tag name, we will set the tag name default to `latest`, because it will automatically fetch the latest tag if you create an image stream without specifying the tag name
3. If the user inputs the tag name, we will set the tag name of the BYON image to the same as the tag name user is importing

Because some docker container images might not have the `latest` tag or might not have the tag user specifies, it could throw an error if the tag cannot be found. In this situation, we show the error in the BYON image table to the admin users and hide the image from the spawner page of both the KFNBC and DS projects.

UX/UI change: Add an error state and tooltip to invalid BYON images

Screenshot 2023-05-17 at 9 50 18 AM

## How Has This Been Tested?

1. Try to create some custom images, you can use the images here https://quay.io/repository/opendatahub/workbench-images?tab=tags with the tag starting with `jupyter`, also you can go to search the OpenShift internal image streams like `image-registry.openshift-image-registry.svc:5000/opendatahub/s2i-minimal-notebook`. Try to create some with and without the tags
2. Go to the spawner page to see if you can create a notebook/workbench with the custom image
3. Try to find an image without the `latest` tag and import that image without specifying the tag
4. Check whether there is an error state in the table for that image
5. Check whether the error image is not visible in the spawner page image selections

## Test Impact

Add some jest tests to make sure the regex could parse the URL correctly.

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

File: backend/src/utils/constants.ts [hunk 1]
```diff
@@ -130,3 +130,6 @@ export const DEFAULT_NOTEBOOK_SIZES: NotebookSize[] = [
     },
   },
 ];
+
+export const imageUrlRegex =
+  /^([\w.\-_]+((?::\d+|)(?=\/[a-z0-9._-]+\/[a-z0-9._-]+))|)(?:\/|)([a-z0-9.\-_]+(?:\/[a-z0-9.\-_]+|))(?::([\w.\-_]{1,127})|)/;
```
Comment (DaoDaoNoCode) [inline backend/src/utils/constants.ts:135]: This regex won't match `@sha256...` as the tag because if use that, we cannot set it as the tag name. So in the custom image, the tag name will be set to `latest` but the repo URL will be set to the correct one with `@sha256`.

**Comment by DaoDaoNoCode** [comment]
@vconzola Please check the UI change for the error state of the custom images as listed in the description.

File: backend/src/routes/api/images/imageUtils.ts [hunk 2]
```diff
@@ -91,6 +90,18 @@ const getImageStreams = async (
...
+const isBYONImage = (imageStream: ImageStream) =>
+  imageStream.metadata.labels?.['app.kubernetes.io/created-by'] === 'byon';
+
+const getBYONImageErrorMessage = (imageStream: ImageStream) => {
+  // there will be always only 1 tag in the spec for BYON images
+  // status tags could be more than one
+  const activeTag = imageStream.status?.tags?.find(
+    (statusTag) => statusTag.tag === imageStream.spec.tags?.[0].name,
+  );
+  return activeTag?.items === null ? activeTag.conditions?.[0].message : undefined;
```
Comment (lucferbux) [inline backend/src/routes/api/images/imageUtils.ts:102]: Just out of curiosity, cause i couldn't validate it checking the spec. Why do you need items to be null to get the error message? Is it possible to have an issue with the status filled with items? Why not try to access `activeTag.conditions?.[0].message` and fallback to undefined if you could not get it?

File: frontend/src/__tests__/dockerRepositoryURL.spec.ts [hunk 3]
```diff
@@ -0,0 +1,50 @@
+// https://cloud.google.com/artifact-registry/docs/docker/names
+// The full name for a container image is one of the following formats:
+// LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY/IMAGE
+// LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY/IMAGE:TAG
+// LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY/IMAGE@IMAGE-DIGEST
+
+const repositoryUrlRegex =
+  /^([\w.\-_]+((?::\d+|)(?=\/[a-z0-9._-]+\/[a-z0-9._-]+))|)(?:\/|)([a-z0-9.\-_]+(?:\/[a-z0-9.\-_]+|))(?::([\w.\-_]{1,127})|)/;
```
Comment (lucferbux) [inline frontend/src/__tests__/dockerRepositoryURL.spec.ts:8]: Why don't you reference. `imageUrlRegex`, that way, if it changes, we can detect it in this test.

File: frontend/src/pages/projects/screens/spawner/spawnerUtils.ts [hunk 4]
```diff
@@ -376,3 +376,15 @@ export const checkRequiredFieldsForNotebookStart = (
     isDataConnectionValid
   );
 };
+
+export const isInvalidBYONImageStream = (imageStream: ImageStreamKind) => {
+  // there will be always only 1 tag in the spec for BYON images
+  // status tags could be more than one
+  const activeTag = imageStream.status?.tags?.find(
```
Comment (lucferbux) [inline frontend/src/pages/projects/screens/spawner/spawnerUtils.ts:383]: You are getting the activeTag in several parts, we might want to convert this into a function right?

**Review by lucferbux — CHANGES_REQUESTED** [review]

File: backend/src/routes/api/images/imageUtils.ts (hunk 2 above)
Comment (DaoDaoNoCode) [reply backend/src/routes/api/images/imageUtils.ts:102]: hmm, good catch. I will change it. I cannot validate the status spec too.

**Comment by vconzola** [comment]
@DaoDaoNoCode As long as invalid images are hidden from non-admin users in the spawner dropdowns, the UX LGTM.

File: backend/src/routes/api/images/imageUtils.ts [hunk 5]
```diff
@@ -207,7 +216,14 @@ export const postImage = async (
   const customObjectsApi = fastify.kube.customObjectsApi;
   const namespace = fastify.kube.namespace;
   const body = request.body as BYONImageCreateRequest;
-  const imageTag = body.url.split(':')[1];
+  const fullUrl = body.url;
+  const matchArray = fullUrl.match(imageUrlRegex);
+  // check if the host is valid
+  if (!matchArray[1]) {
+    fastify.log.error('Invalid repository URL unable to add notebook image');
+    return { success: false, error: 'Invalid repository URL: ' + fullUrl };
```
Comment (lucferbux) [inline backend/src/routes/api/images/imageUtils.ts:224]: I guess that's the way we had the endpoint configure, but I'm not a fan of returning a 200 with a failing state, rather than using the proper error code.

**Review by lucferbux — APPROVED** [review]
/lgtm

I left a little nit,  but at this point I don't think we should do major refactors to the backend so it's ok.

File: backend/src/routes/api/images/imageUtils.ts (hunk 5 above)
Comment (andrewballantyne) [reply backend/src/routes/api/images/imageUtils.ts:224]: Yeah, there is a lot of uncomfortable stuff with this area of the code -- I'm viewing the UI and noticing a lot of inconsistencies to the other parts of our app... we will need to rework this.

File: backend/src/utils/constants.ts (hunk 1 above)
Comment (andrewballantyne) [reply backend/src/utils/constants.ts:135]: Oh my gosh -- we need you to comment this in some fashion haha... wowzers, that's a regex and a half haha.

File: frontend/src/pages/BYONImages/ImageErrorStatus.tsx [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+  image: BYONImage;
+};
+
+const ImageErrorStatus: React.FC<ImageErrorStatusProps> = ({ image }) => {
+  if (!image.error) {
+    return null;
+  }
+  return (
+    <Tooltip removeFindDomNode role="none" content={<Text>{image.error}</Text>}>
+      <Icon role="button" aria-label="error icon" status="danger" isInline tabIndex={0}>
```
Comment (andrewballantyne) [inline frontend/src/pages/BYONImages/ImageErrorStatus.tsx:16]: I feel this is not the best way to make it tab-enabled... because you're explicitly setting the tab index to 0. We did this elsewhere with a button: https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/components/SupportedAppTitle.tsx#L22-L30

**Review by andrewballantyne — APPROVED** [review]
Will log a tech debt to clean up some of these things... this is bad for maintenance, but this works as-is... so we'll want to clean it up next sprint.
