### PR TITLE
Modify Accelerator support for kserve

### LINKED ISSUE #2244: [Bug]: Accelerator enablement in kserve is not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

2.5.0

### Current Behavior

We are currently assigning gpu resources to all the containers in a ServingRuntime spec for KServe, this has been ok for `Modelmesh` but it's creating an issue where we add more resources than the cluster might have.

### Expected Behavior

The outcome will be the following:

#### For modelmesh
Keep the same flow and get the creation of `InferenceServices` and `ServingRuntimes` as it is right now

#### For kserve

1. Remove the assignation of tolerations and GPU resources in the containers of the serving runtime, for that add a conditional and just add them for modelmesh.
2. Add that logic for inferenceservices:
   * Add tolerations in `spec.predictor.tolerations` such as [this example](https://kserve.github.io/website/0.11/modelserving/nodescheduling/inferenceservicenodescheduling/#tolerations)
   * Add the GPU resrouces in the `spec.predictor-model-resources` section

### Steps To Reproduce

1. Creaate a new project with accelerator
2. Deploy a kserve model
3. Select the maximum number of accelerator nodes

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Closes #2244 

### Prerequisites
Enable accelerator support in your cluster, you can add this accelerator into your cluster:

```yaml
apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  name: migrated-gpu
  namespace: redhat-ods-applications
spec:
  displayName: Nvidia GPU
  enabled: true
  identifier: nvidia.com/gpu
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
```

### KServe Resource Creation

1. Deploy a new KServe model selecting the accelerator and a number of nodes
2. Check the `ServingRuntime` spec. **It shouldn't contain** tolerations, neither the gpu requests/limits `nvidia.com/gpu`
3. Check the `InferenceService` spec. **It should contain** tolerations under `spec.predictor.tolerations` and the gpu request/limits under `spec.predictor.model.resources`

### KServe Resource Editing

1. Edit the model deployed and remove the accelerator
2. Check the `ServingRuntime` spec. **It shouldn't be the same, just removing the opendatahub.io/accelerator-name label**
3. Check the `InferenceService` spec. **It shouldn't contain** tolerations under `spec.predictor.tolerations` neither the gpu request/limits under `spec.predictor.model.resources`

### Modelmesh Resrouce Creation

1. Create a new modelmesh server and select accelerator
2. Check the `ServingRuntime` spec. **It should contain tolerations and gpu resources**
3. Deploy a model
4. Check the `InferenceService` spec. **It shouldn't contain any gpu resource**

## Test Impact

Covered all paths with unit testing

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

**I haven't tested this changes with a proper gpu cluster, we should do that asap**

### CODE REVIEW

**Review by Xaenalt — APPROVED** [review]

File: frontend/src/__mocks__/mockAcceleratork8sResource.ts
Comment (andrewballantyne) [inline frontend/src/__mocks__/mockAcceleratork8sResource.ts:1]: cc @Gkrumbach07 I believe this is done in your Feature branch, FYI.

File: frontend/src/k8sTypes.ts [hunk 1]
```diff
@@ -378,11 +378,13 @@ export type InferenceServiceKind = K8sResourceCommon & {
   };
   spec: {
     predictor: {
+      tolerations?: PodToleration[];
       model: {
```
Comment (andrewballantyne) [inline frontend/src/k8sTypes.ts:382]: wasn't this the _type_ ? not actually the text `model`?

I don't have the doc link anymore ... but I thought this was something like `triton` or something like that... I may be mis-remembering, so ignore me if I am.

**Review by andrewballantyne — COMMENTED** [review]
Looking good, one question...

File: frontend/src/__mocks__/mockAcceleratork8sResource.ts
Comment (Gkrumbach07) [reply frontend/src/__mocks__/mockAcceleratork8sResource.ts:1]: https://github.com/opendatahub-io/odh-dashboard/blob/f/accelerator-admin-support/frontend/src/__mocks__/mockAcceleratorProfile.ts

File: frontend/src/k8sTypes.ts (hunk 1 above)
Comment (lucferbux) [reply frontend/src/k8sTypes.ts:382]: That's a great question, we've had the model placeholder for modelmesh and there are examples with model, but ill defer to @Xaenalt and @Jooho that question.

File: frontend/src/__mocks__/mockAcceleratork8sResource.ts
Comment (Gkrumbach07) [reply frontend/src/__mocks__/mockAcceleratork8sResource.ts:1]: ok. Im fine with merging main again. yours is going in first so ill just react to it

File: frontend/src/k8sTypes.ts (hunk 1 above)
Comment (Jooho) [reply frontend/src/k8sTypes.ts:382]: @andrewballantyne I think you saw this kind of example
~~~
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "flower-sample"
spec:
  predictor:
    tensorflow:
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers"
~~~
It is an old Schema. The new schema looks like this:
~~~
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "flower-sample"
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers"
~~~

Doc:https://kserve.github.io/website/0.10/modelserving/v1beta1/tensorflow/

**Review by andrewballantyne — APPROVED** [review]
Sounds good... type question was resolved. LGTM.
