### PR TITLE
Remove logic - kube:admin as default username

### LINKED ISSUE #360: [Bug]: Default user fallback to "kube:admin"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now, when fetching the user, if both **oauth proxy's header** and **openshift user username** are empty the dashboard will fallback the username to `kube:admin`.

### Expected Behavior

Maybe if we cannot find the User we need to raise an exception and raise an error in the frontend.

### Steps To Reproduce

_No response_

### Workaround (if any)

_No response_

### OpenShift Version

_No response_

### Openshift Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Fixes #360 

## How Has This Been Tested?

1. Install this image.
2. Deploy in the cluster.
3. Force an oauth proxy error.
4. Check that you reach the error page.

Screenshot 2022-09-09 at 17 16 15

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by andrewballantyne** [comment]
I renamed the PR -- it will be less alarming. Maybe we also change the commit message so it doesn't show up as `delete kube:admin...` in the commit tree

File: backend/src/utils/userUtils.ts [hunk 1]
```diff
@@ -53,7 +53,10 @@ export const getUserName = async (
     const userOauth = await getUser(request, customObjectsApi);
     return userOauth.metadata.name;
   } catch (e) {
-    const userCluster = (currentUser.username || currentUser.name)?.split('/')[0];
-    return !userCluster || userCluster === 'inClusterUser' ? DEFAULT_USERNAME : userCluster;
+    if (DEV_MODE) {
+      return (currentUser.username || currentUser.name)?.split('/')[0];
+    }
+    fastify.log.error(`Error retrieving username, ${e.toString()}`);
```
Comment (andrewballantyne) [inline backend/src/utils/userUtils.ts:59]: Avoid `e.toString()` -- we should look to do `e.response.body.message` to get the k8s error. If it's our own error throw from a lower method, `e.message`... support both instead of `e.toString()` as it will most likely swallow the actual error and not print it in the logs.

File: backend/src/routes/api/groups-config/index.ts [hunk 2]
```diff
@@ -6,7 +6,10 @@ export default async (fastify: FastifyInstance): Promise<void> => {
   fastify.get('/', async () => {
     return getGroupsConfig(fastify);
   });
-  fastify.put('/', async (request: FastifyRequest<{ Body: GroupsConfig }>) => {
-    return updateGroupsConfig(fastify, request);
+  fastify.put('/', async (request: FastifyRequest<{ Body: GroupsConfig }>, reply) => {
+    return updateGroupsConfig(fastify, request).catch((e) => {
+      fastify.log.error(`Failed to update groups configuration, ${e.toString()}`);
```
Comment (andrewballantyne) [inline backend/src/routes/api/groups-config/index.ts:11]: Same here

File: backend/src/routes/api/status/index.ts [hunk 3]
```diff
@@ -9,6 +9,7 @@ export default async (fastify: FastifyInstance): Promise<void> => {
         return res;
       })
       .catch((res) => {
+        fastify.log.error(res);
```
Comment (andrewballantyne) [inline backend/src/routes/api/status/index.ts:12]: Always add additional text before the log -- sometimes errors can be really unhelpful to showing where they came from.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
I agree we should probably just error out when there is an issue getting the username.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
I think this solution works fine. Only concern I have is this bulk of this logic actually is not first called in our secure route layer. This will blow up before any call can do anything because we need your username to vet your access to resources.

I'm not sure anything can be done to improve this if we want our security layer the way it is. If this fails, it obscures what happened on the frontend (for dev, just remove your if-statement in the catch).

All I got when I intentionally caused this to happen was `Something went wrong` -- I'd like this to be better if possible -- @lucferbux can you look at a way to get that error to bubble up on the client somehow? Maybe we make a specific route to get username that we call before anything else on the frontend? Think outside the box, I'll look into this tomorrow again and see if I can think of a solution (if one is not already implemented).

**Review by andrewballantyne — APPROVED** [review]
Looks good...

/hold
Want to test the PR to make sure it works, but if others test it feel free to unhold.

**Review by dlabaj — APPROVED** [review]
/lgtm
