### PR TITLE
Compare workbench size correctly and add error message

### LINKED ISSUE #826: [Bug]: Sometimes Workbenches have an 'Unknown' Container Size
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In some cases there is a problem getting the container size.

image

Best guess is it is possibly related to the original name? `notebookId` [variable](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/api/network/notebooks.ts#L137) path should be traced. 

### Expected Behavior

Should always say what the name is, or we should have some error flow state to say why it is not there. This will be a crap shoot to determine why this is happening. Best we can do is try to investigate the path and also provide an error flow when we can't find it. 

Error icon with a tooltip is a standard flow to showcase why we failed to find it. See the `null` paths in [useNotebookDeploymentSize](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts)

### Steps To Reproduce

Unknown. Check the RHODS ticket when starting.
https://issues.redhat.com/browse/RHODS-6055

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
2.5.1
```

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
## Description

Closes #826 
When the size cannot be correctly found, we have an error tooltip next to the size which might give you some hint on what's the problem.
Screenshot 2023-01-10 at 4 08 49 PM

## How Has This Been Tested?

For GPUs:
Add GPU to workbench -> Make sure the size is not unknown
For error messages:
Create a workbench -> Change the size in dashboard config CR -> See the error icon and hover to see the tooltip

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts [hunk 1]
```diff
@@ -1,33 +1,38 @@
...
+      size.resources.limits?.cpu === container.resources?.limits?.cpu &&
+      size.resources.limits?.memory === container.resources?.limits?.memory,
+  );
 
   if (!size) {
-    return null;
+    return {
+      size: null,
+      error:
+        'Failed to get size information, the size might be changed after the workbench creation, please check your dashboard config.',
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts:31]: @kywalker-rh thoughts on wording?

**Review by andrewballantyne — APPROVED** [review]
Looks good to me. Solves the issue and exposes the error so the user can understand more why we can't find the container size.

File: frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts (hunk 1 above)
Comment (kywalker-rh) [reply frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts:31]: I like the solution, thanks for putting that together @DaoDaoNoCode! I can't think of any changes, but tagging @kaedward in case she has feedback.

Comment (andrewballantyne) [reply frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts:31]: If Katie would like any changes, we can do another PR. I think we have enough eyeballs on this to consider this a good first state.

Comment (kaedward) [reply frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts:31]: @andrewballantyne @kywalker-rh Does this happen when the workbench size is changed from the dashboard and it hasn't updated on the screen yet? If that's the case, I'd suggest something along the lines of "Workbench size is currently unavailable. Check your dashboard configuration to view size information, or refresh the page."

LMK if I'm not fully understanding the issue here!

Comment (andrewballantyne) [reply frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts:31]: @kaedward It is when you create a Workbench -- then at some point after change the Notebook Size value in the ODHDashboardConfig -- since it's only the value we store in the Workbench, we reverse engineer the name of the Notebook Size by matching it 1:1 with the values for the resource limits. 

So it's not currently something they can configure in the Dashboard, but it is a logical state the code can get into.

**Comment by andrewballantyne** [comment]
Removing hold. If Katie comes up with a more preferred wording we can circle back.

**Comment by andrewballantyne** [comment]
/hold

Wait, actually, let us modify to match what Katie said -- if it needs more after that we can circle back.

File: frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts (hunk 1 above)
Comment (andrewballantyne) [reply frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts:31]:
```suggestion
        'Workbench size is currently unavailable. Check your dashboard configuration to view size information.',
```
@DaoDaoNoCode Please do this change.

**Review by andrewballantyne — APPROVED** [review]
