### PR TITLE
Fixes error Cluster admin does not get RHODS Admin access if it's the…

### LINKED ISSUE #613: [Bug]: Cluster admin does not get Admin access if it's the only user in the cluster
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It looks like when the cluster admin is the only user present in the cluster, it doesn't get the Admin access automatically. 
The dashboard pod reports these lines of error about rolebindings:

```
{"level":50,"time":1664785629417,"pid":108,"hostname":"rhods-dashboard-59bb5c9d89-6kb2f","msg":"Failed
 to list rolebindings for user, Failed to list groups filtered by 
username."}{"level":50,"time":1664785629436,"pid":108,"hostname":"rhods-dashboard-59bb5c9d89-6kb2f","msg":"Failed
 to list rolebindings for user, Failed to list groups filtered by 
username."}
```
...
As soon as we created more users, it got the permissions and the logs stopped to show those errors about role binding.
 

### Expected Behavior

Having admin access regardless the number of users

### Steps To Reproduce

1. Create a cluster (reproduced on OSD)
2. Create only one user with cluster admin permissions (no other users in the cluster)
3. Log in the Dashboard using the cluster admin
4. Check if the user can access the "Settings" section
5. create new users
6. Check point 4) once again

### Workaround (if any)

* Add more than one users

### OpenShift Infrastructure Version

_No response_

### Openshift Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by lucferbux**
… only user in the cluster

## Description

Fixes #613

## How Has This Been Tested?

1. Delete all the users of the cluster except one
2. Create a group with no users
3. Check that it's not breaking

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: backend/src/utils/groupsUtils.ts [hunk 1]
```diff
@@ -96,8 +96,8 @@ export const getAllGroupsByUser = async (
       'groups',
     );
     const groups = adminGroupResponse.body as GroupCustomObject;
-    return groups.items.filter((x) => x.users.includes(username)).map((x) => x.metadata.name);
+    return groups.items.filter((x) => x.users?.includes(username)).map((x) => x.metadata?.name);
```
Comment (DaoDaoNoCode) [inline backend/src/utils/groupsUtils.ts:99]: If the `users` are not always an array and could be `undefined`, could you also add this to the `GroupCustomObjectItem` type `users?: string[];`. And the same for `metadata`, if it's always defined, you may not need the `?` but if it could be `undefined` you may also want to change its type definition.

Comment (lucferbux) [reply backend/src/utils/groupsUtils.ts:99]: Yes, i thought about it tx! I'll add it

File: backend/src/utils/groupsUtils.ts [hunk 2]
```diff
@@ -65,7 +65,8 @@ export const getGroup = async (
       'groups',
       adminGroup,
     );
-    return (adminGroupResponse.body as GroupObjResponse).users;
+    const users = (adminGroupResponse.body as GroupObjResponse).users;
```
Comment (DaoDaoNoCode) [inline backend/src/utils/groupsUtils.ts:68]:
```suggestion
    return (adminGroupResponse.body as GroupObjResponse).users || [];
```

**Review by DaoDaoNoCode — APPROVED** [review]
lgtm
