### PR TITLE
Automatically generate first token when enable route when adding modelmesh server

### LINKED ISSUE #2049: [Story]: Regression in modelmesh modal for tokens
### Goal

In `ManageServingRuntimeModal` we have a regression when selecting `Token authorization`, it no longer automatically generates the first token

### Dependency issue

No dependencies

### Itemized goals

1. Fix a regression
2. To reproduce, create a new Model Server in modlemesh
3. Select token authorization
4. It should present a default token, but right now it's not there

### Aspects continued elsewhere

_No response_

### Mocks

No mocks

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #2049 

## Description

In https://github.com/opendatahub-io/odh-dashboard/pull/1862, we automatically check the `token authorization` checkbox when the route is enabled. However, we didn't add the default service account in this action. This PR is to fix that issue.

## How Has This Been Tested?

1. Go to a model-mesh project
2. Add a model server
3. Check the Model Route section
4. Make sure the token authorization is also checked and a default service account is added

## Test Impact

Add a check in the integration test to make sure the service account token is added

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx [hunk 1]
```diff
@@ -138,6 +139,20 @@ const ManageServingRuntimeModal: React.FC<ManageServingRuntimeModalProps> = ({
       });
   };
 
+  const createNewToken = React.useCallback(() => {
```
Comment (lucferbux) [inline frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx:142]: Yeah, great idea moving the addition logic from the component, it will be more reusable.

**Review by lucferbux — APPROVED** [review]
/lgtm
