### PR TITLE
Show non-DS projects in the project table

### LINKED ISSUE #1310: [Bug]: Delay Model Serving Annotation until First Server
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Today, we create every namespace with the expectation of Model Serving.

We should delay the adding of the `modelmesh-enabled` label until we reach the point of Model Server creation.

This can create scale issues, as this NetworkPolicy relies on this label to define network flow rules:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels: ...
  name: etcd
  namespace: redhat-ods-applications
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          modelmesh-enabled: "true"
    ports:
    - port: 2379
      protocol: TCP
  podSelector:
    matchLabels:
      app: model-mesh
      app.kubernetes.io/part-of: model-mesh
      component: model-mesh-etcd
  policyTypes:
  - Ingress
```

### Expected Behavior

Delay labelling of project until we need it.

### Steps To Reproduce

1. Create Project
2. View Labels on Project

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
Dashboard: v2.7.0
```

### Anything else

_No response_

### LINKED ISSUE #1417: Create data science project in existing namespace
## Solution

We'll be supporting OpenShift Console Projects in the Dashboard.

Mocks: https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=287%3A13618&type=design&node-id=287-14414&viewport=273%2C151%2C0.06&t=qM4W6hZAcZiZPXig-1&scaling=scale-down&starting-point-node-id=287%3A14414&mode=design

Implementation notes:

Follow the design, but here are a couple expected items for the development effort.

* Do two types of fetches -- one with the labelSelector (`opendatahub.io/dashboard`) and one without -- RBAC will help the user see all the namespaces that belong to them
* If the results come back with anything `openshift-` or `kube` prefixed or `default` namespace... trim them out before saving the data
* The create flow does not change
* Store the last selected value of the dropdown in local storage (`useBrowserStorage` hook should make this easy)

---

## Enhancement request
Allow the creation of data science project to specify an existing namespace. Currently DSP name cannot be the same to another existing namespace in the Openshift Cluster. 
### Details
Namespace is used to manage users and enforce cluster resource usage quota, e.g. the maximum numbers of CPUs, GPUs, pods. Creating new namespaces requires OCP admins to redo user binding and quota configuration.

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1417 
Closes #1310 

## Description

Add a select field, allowing the user to select the scope of the project table.
When selecting Data science projects:

Screenshot 2023-08-07 at 3 50 00 PM

When selecting All available projects:

Screenshot 2023-08-07 at 3 53 45 PM

Also, only apply the `modelmesh-enabled: 'true'` annotation when first creating a server in a project.

## How Has This Been Tested?

1. Go to the dashboard projects page
2. Toggle the select dropdown to view different scopes
3. Make sure projects starts with `openshift-` or `kube-` or `default` or `system` or `openshift` or the dashboard namespace are not shown in the list
4. Try to create a workbench in a non-DS project

## Test Impact

TBD

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
I have some questions about RBAC for this PR that needs more information or answers.
1. Does the scope limit access to the specific project? For example, if an admin user has access to some non-DS projects, and he sets the scope to `Data science projects`, now he can only see DS projects in the list. However, can he access the project details page of a non-DS project by typing in the URL? Currently, in this implementation he can, because we only limit the scope filter from a UI perspective, but we didn't set any RBAC limitation.
2. Does the scope affects other pages like Data science pipelines? For example, on the DS pipelines page, you will need to select a project to create a pipeline. If the user limits the scope to DS projects only, can he still see the non-DS projects in this list? Currently, we don't do any filters here. Do we want to only show DS projects here no matter what scope the user chooses on the projects page or do we want to show the projects based on the user's choice of scope?
Screenshot 2023-08-07 at 4 41 09 PM

File: frontend/src/concepts/projects/ProjectsContext.tsx [hunk 1]
```diff
@@ -44,37 +46,51 @@ type ProjectsProviderProps = {
...
-              // Model Serving active projects
-              states.modelServingProjects.push(project);
+          if (
+            !(
+              project.metadata.name.startsWith('openshift-') ||
+              project.metadata.name.startsWith('kube-') ||
+              project.metadata.name === 'default' ||
+              project.metadata.name === 'system' ||
+              project.metadata.name === 'openshift'
+            )
```
[the remark this answers is not in the document]
Comment (lucferbux) [reply frontend/src/concepts/projects/ProjectsContext.tsx:73]: Mmmmmm, not sure if we want to show the default projects of the dashboard, that's something we might want to discuss, although we can do a follow up (I'm talking that in upstream we might wanna remove `opendatahub`)

File: frontend/src/concepts/projects/ProjectsContext.tsx [hunk 2]
```diff
@@ -44,37 +46,51 @@ type ProjectsProviderProps = {
 };
 
 const ProjectsContextProvider: React.FC<ProjectsProviderProps> = ({ children }) => {
-  const fetchProjects = React.useCallback(() => getDSGProjects(), []);
+  const fetchProjects = React.useCallback(() => getProjects(), []);
```
Comment (lucferbux) [inline frontend/src/concepts/projects/ProjectsContext.tsx:49]: mmmm I think this is the simplest solution, but might induce into some performance issues, if a user just want to list ds projects, it will wait until all the projects are loaded, which is not ideal.
I get that is way easier filtering client side, so for me it's not a blocker and I can lgtm this, but it's something we might wanna take a look or maybe do a follow up in the future.

**Review by lucferbux — APPROVED** [review]
/lgtm

Code looks great and the PR is mostly doing what the description of the issue is asking. 
I have some concerns, such as displaying the dashboard namespace and the fact that I'm not sure if the issue itself was asking to have the ability to convert a non ds project into one (this pr doesn't have that logic but I don't see that flow in the requirements nor the mocks).

I can stamp an approval but I would love to have further conversations about this.

File: frontend/src/pages/ApplicationsPage.tsx [hunk 3]
```diff
@@ -16,6 +16,7 @@ import {
   PageBreadcrumb,
   StackItem,
   Stack,
+  Divider,
```
[the remark this answers is not in the document]
Comment (DaoDaoNoCode) [reply frontend/src/pages/ApplicationsPage.tsx:19]: Sounds fair, I will leave this issue to the UX team.

**Comment by lucferbux** [comment]
/hold

This issue will slip to next sprint, we've changed the priorities and we'll only merge bug fixes.

**Comment by kywalker-rh** [comment]
@xianli123 - This is to implement your design so please take a look when you get a chamce.

File: frontend/src/pages/ApplicationsPage.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (xianli123) [reply frontend/src/pages/ApplicationsPage.tsx:19]: Hi @DaoDaoNoCode @manaswinidas I have checked the discussion about the divider. In the [this Slack thread](https://redhat-internal.slack.com/archives/C043A9D5DMW/p1690464106905299), the final decision is to remove the devider. So I think we can follow that and it should be consistent with other pages. Thanks for pointing it out.

**Comment by xianli123** [comment]
@kywalker-rh Thanks. The UI looks good to me. As for the divider, it can be removed, as decided in [this Slack thread](https://redhat-internal.slack.com/archives/C043A9D5DMW/p1690464106905299).

**Comment by DaoDaoNoCode** [comment]
Based on the discussion we had in the UX meeting, we are not going to block/filter any OpenShift projects, we will fetch whatever we get and show them to the users. Most of the users are developers only, and RBAC will prevent them from seeing the OpenShift default projects. As for admin users, they should know what they are doing so there is no harm to show all the projects to them :)

File: frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx [hunk 4]
```diff
@@ -28,9 +28,16 @@ const ProjectTableRow: React.FC<ProjectTableRowProps> = ({
   return (
     <Tr>
       <Td dataLabel="Name">
-        <ResourceNameTooltip resource={project}>
-          <ProjectLink project={project} />
-        </ResourceNameTooltip>
+        <Flex spaceItems={{ default: 'spaceItemsXs' }} alignItems={{ default: 'alignItemsCenter' }}>
+          {project.metadata.labels?.[KnownLabels.DASHBOARD_RESOURCE] && (
+            <Label isCompact color="green">
+              DS
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx:34]: We might want a tooltip saying this is `Data Science` -- `DS` is well known by us, but will it be by the users? cc @kywalker-rh (I don't know Kun's gh handle)

File: frontend/src/typeHelpers.ts [hunk 5]
```diff
@@ -93,3 +93,8 @@ export type EitherNotBoth<TypeA, TypeB> = (TypeA & Never<TypeB>) | (TypeB & Neve
 export type EitherOrNone<TypeA, TypeB> =
   | EitherNotBoth<TypeA, TypeB>
   | (Never<TypeA> & Never<TypeB>);
+
+export const isSomeEnum =
```
Comment (andrewballantyne) [inline frontend/src/typeHelpers.ts:97]: Um.... Why? Help me understand why we need to dynamically check a static state of if it's a TypeScript enum?

Comment (andrewballantyne) [reply frontend/src/typeHelpers.ts:97]: Oooooh, I misread the use -- you're checking if it's IN the enum... this is a bad named function. `isInEnum` is probably better. Currying functions might have some other naming strategy, but I think that's better than "is this an enum" sounding function.

File: frontend/src/concepts/projects/ProjectsContext.tsx [hunk 6]
```diff
@@ -44,25 +46,29 @@ type ProjectsProviderProps = {
...
+        dataScienceProjects: ProjectKind[];
         modelServingProjects: ProjectKind[];
         nonActiveProjects: ProjectKind[];
       }>(
         (states, project) => {
           if (project.status?.phase === 'Active') {
             // Project that is active
             states.projects.push(project);
+            if (project.metadata.labels?.[KnownLabels.DASHBOARD_RESOURCE]) {
+              states.dataScienceProjects.push(project);
```
Comment (andrewballantyne) [inline frontend/src/concepts/projects/ProjectsContext.tsx:70]: Now that you're fetching everything -- you need to trim out `openshift-` and `kube-`, as well as remove `default` -- these are not valid projects.

File: frontend/src/concepts/projects/ProjectsContext.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (andrewballantyne) [reply frontend/src/concepts/projects/ProjectsContext.tsx]: Was this snippet removed? I can't find it in the changeset...

File: frontend/src/concepts/projects/ProjectsContext.tsx (hunk 6 above)
Comment (DaoDaoNoCode) [reply frontend/src/concepts/projects/ProjectsContext.tsx:70]: We had the discussion in the UX meeting last week, it's a short one and you could go back to check that, I think we came to the agreement at last we are not going to filter any projects. I also added it here in the comment https://github.com/opendatahub-io/odh-dashboard/pull/1643#issuecomment-1678941615

File: frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx (hunk 4 above)
Comment (andrewballantyne) [reply frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx:34]: cc @xianli123 👋

File: frontend/src/concepts/projects/ProjectsContext.tsx (hunk 6 above)
Comment (andrewballantyne) [reply frontend/src/concepts/projects/ProjectsContext.tsx:70]: I'm going to have to overrule that -- absolutely not a good idea. I'll watch the recording (still on my todo list) but we 100% do not want to expose that in our UI -- accidental misuse of this projects is a *bad* idea.

**Comment by andrewballantyne** [comment]
/hold

Yeah, holding this until we can discuss the "showing of infrastructure projects" in the Dashboard. I disagree with the stance made in the UX meeting last week.

File: frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx (hunk 4 above)
Comment (xianli123) [reply frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx:34]: @andrewballantyne That makes sense. Adding a dedicator is a good way.

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm

**Comment by DaoDaoNoCode** [comment]
@christianvogt I am wondering whether this could go through the merge process because I changed the target branch halfway 🤔

**Comment by DaoDaoNoCode** [comment]
Manually add `approved` label to see if the merge could happen.
