### PR TITLE
Custom serving runtimes: fix drag problems, add deleting and editing features

### LINKED ISSUE #1083: Allow edit or remove a Serving Runtime
## Feature description

Allow users to edit and remove available Serving Runtimes Templates.

### Continuation of

- https://github.com/opendatahub-io/odh-dashboard/issues/1077
- https://github.com/opendatahub-io/odh-dashboard/issues/1080

### Tasks

- Add `edit` and `delete` actions to the rows
- Add the ability to delete a Serving Runtime
- Open the Custom Runtime creation page for editing a current Serving Runtime

### Follow up issues

- https://github.com/opendatahub-io/odh-dashboard/issues/1180

### Mocks

- https://www.sketch.com/s/5c26573b-fd37-4d54-a4f7-aab1cc17ff5d/a/g10xeOj

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1083 

## Description

1. Fix some drag-and-drop issues and remove the debounce for it.
2. Add the "delete" dropdown in the kebab toggle. When you click on it, you can open a deleting modal to delete the serving runtimes
Screenshot 2023-04-26 at 9 20 23 PM
3. Add the "edit" dropdown in the kebab toggle. When you click on it, it will take you to the same page as you adding the serving runtimes, but it will read the current information and map them in the code editor so you can update it.
Screenshot 2023-04-26 at 9 23 00 PM

## How Has This Been Tested?

1. Try to drag and drop to see if there are any bugs
2. Try to create a serving runtime and delete it
3. Try to create a serving runtime and edit it, you can add the `openshift.io/display-name` field in the annotation so it will show the display name. Otherwise, it will show the metadata name.

## Test Impact

Will add tests after everything is done.

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

File: frontend/src/api/k8s/templates.ts [hunk 1]
```diff
@@ -20,20 +21,23 @@ export const assembleTemplate = (body: string, namespace: string): TemplateKind
...
+      // user could change the template with a new serving runtime
+      // and create an other template with the old serving runtime
+      // if we keep the name, there could be a conflict
       namespace,
       labels: {
         'opendatahub.io/dashboard': 'true',
       },
       annotations: {
-        description,
+        'openshift.io/description': description,
```
Comment (DaoDaoNoCode) [inline frontend/src/api/k8s/templates.ts:40]: @lucferbux I changed this to `openshift.io/description` to make it more aligned with the current design so we can use `getDescriptionFromK8sResource` method.

File: frontend/src/api/k8s/templates.ts [hunk 2]
```diff
@@ -101,3 +111,44 @@ export const createServingRuntimeTemplate = (
...
+        queryOptions: { name, ns: namespace },
+        patches: [
+          {
+            op: 'replace',
+            path: '/metadata/annotations/openshift.io~1description',
+            value: getDescriptionFromK8sResource(template),
+          },
+          {
+            op: 'replace',
+            path: '/metadata/annotations/openshift.io~1display-name',
```
Comment (DaoDaoNoCode) [inline frontend/src/api/k8s/templates.ts:134]: We don't check display name for the templates so there could be the rows showing the same name if they have different metadata name and same display name. Let me know your thoughts @lucferbux @vconzola
Screenshot 2023-04-26 at 9 28 41 PM

Comment (vconzola) [reply frontend/src/api/k8s/templates.ts:134]: If possible, we should detect this condition and alert the the user - e.g., "A runtime with this name already exists. To avoid duplicate names appearing in the runtimes table, change the name in the <display_name> field in the YAML file." Action options on the alert modal would be "Ignore and save" and "Cancel". We might also consider adding a "Last saved" column to the table so the user has some way to distinguish between runtimes withe same display name.

Comment (andrewballantyne) [reply frontend/src/api/k8s/templates.ts:134]: cc @kywalker-rh we have no functionality like this -- is this desired throughout?

@vconzola would you be okay not having that first pass? I talk to Kyle A LOT about consistency in the Dashboard. Doing really special and desirable things in one spot sorta softens the holistic nature of the Dashboard. We should aim to support the same functionality _everywhere_ in the dashboard as a single request so the user experience remains consistent and predictable -- imo.

**Comment by vconzola** [comment]
A couple comments re: the two screenshots at the top. 
Consider adding some text to the delete modal that says "Models already deployed using this runtime will not be affected by this action."
What are the three buttons on the left, above the YAML editor? I don't think we need them.

File: frontend/src/api/k8s/templates.ts (hunk 2 above)
Comment (vconzola) [reply frontend/src/api/k8s/templates.ts:134]: Yeah, I'm ok with letting this go for a first pass. But we should add the Last saved column in that case. How are we handling dupes in other parts of the UI - just letting them be? Btw, I would never advocate for consistency over better UX.

Comment (vconzola) [reply frontend/src/api/k8s/templates.ts:134]: Also, not sure what you mean we don't have this feature elsewhere in the UI. I just tried creating duplicate projects with the same name and they get flagged. This situation is unique, however, because the display name is not user generated. It's taken directly from the YAML file, per Chris. (At least I think it was Chris.) If we let the user name their own runtimes we could be consistent with what we're already doing and not allow duplicate names.

Comment (andrewballantyne) [reply frontend/src/api/k8s/templates.ts:134]: I responded [on slack](https://redhat-internal.slack.com/archives/C043A9D5DMW/p1682543093950959) -- this is a process concern, not me blocking UX. See my reply there for my reasoning.

Comment (lucferbux) [reply frontend/src/api/k8s/templates.ts:134]: Just to update the information here:

1. This same situation happens with other resources with display name, if we decide to change it, I would say we track it for the future and do a global refactor.
2. The main issue here lies that [templates](https://docs.openshift.com/container-platform/4.9/openshift_images/using-templates.html) can be misleading if we abstract the user from them, the user is actually filling the spec for a **ServingRuntime** which will be stored in a template, this template has it's own metadata outside the ServingRuntime spec, so the first question would be if we either **update the metadata from the template** or just **treat the serving runtime metadata** as the single source of truth.

**Comment by lucferbux** [comment]
> A couple comments re: the two screenshots at the top. Consider adding some text to the delete modal that says "Models already deployed using this runtime will not be affected by this action." What are the three buttons on the left, above the YAML editor? I don't think we need them.

1. @DaoDaoNoCode not sure if you saw the feedback for the delete modal
2. Those 3 buttons are default actions in the **code editor** component, they can be hidden, the three actions provided are `copy code, upload code and download code` my take here would be at least keep the `upload code`, it could be really handy, since we provide that in the empty state button, but if the user start editing a yaml, there's no flow to go back and upload a new one in the UI, they would need to go back and start again.

File: frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx [hunk 3]
```diff
@@ -82,13 +107,20 @@ const CustomServingRuntimeAddTemplate: React.FC<CustomServingRuntimeAddTemplateP
             <ActionList>
               <ActionListItem>
                 <Button
-                  isDisabled={code === '' || loading}
+                  isDisabled={code === stringifiedTemplate || loading}
```
Comment (lucferbux) [inline frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx:110]: We don't want to remove the `code === ''` check, if so, the button won't be disable is the box is empty.

File: frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeContext.tsx [hunk 4]
```diff
@@ -38,6 +38,7 @@ const CustomServingRuntimeContextProvider: React.FC = () => {
 
   const servingRuntimeTemplateOrder = useContextResourceData<string>(
     useTemplateOrder(dashboardNamespace),
+    2 * 60 * 1000,
```
Comment (lucferbux) [inline frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeContext.tsx:41]: 👍

**Review by lucferbux — CHANGES_REQUESTED** [review]
Most of the changes are fine, the fixes for the drag and drop are working great. 👍

File: frontend/src/api/k8s/templates.ts (hunk 2 above)
Comment (lucferbux) [reply frontend/src/api/k8s/templates.ts:134]: Ok, based on conversations, my take on this would be this one:

1. Leave the Template name alone (maybe random names)
2. Use the Serving Runtime `name` and `display-name` as source of truth
3. When editing, make the Serving Runtime `name` immutable and fail if we intend to modify it

I think that's what I got from the latest conversations, let me know if I misunderstood/missed something @andrewballantyne @DaoDaoNoCode

File: frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx [hunk 5]
```diff
@@ -33,14 +35,36 @@ const CustomServingRuntimeAddTemplate: React.FC<CustomServingRuntimeAddTemplateP
   const [error, setError] = React.useState<Error | undefined>(undefined);
   const navigate = useNavigate();
 
+  const stringifiedTemplate = existingCustomServingRuntime
+    ? YAML.stringify(existingCustomServingRuntime.objects[0])
+    : '';
+
+  React.useEffect(() => {
```
[the remark this answers is not in the document]
Comment (DaoDaoNoCode) [reply frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx:42]: Yeah you are right, I removed it, thanks!

**Comment by DaoDaoNoCode** [comment]
@lucferbux Hi, I made the following updates based on the reviews and feedback:
1. Remove the display name and description annotations in `Template` and generate the template name randomly
2. Use the serving runtime in the template objects as the only source of truth
3. Prevent users from editing the serving runtime name after they create it
Screenshot 2023-04-28 at 3 07 07 PM

4. Prevent users from creating duplicated serving runtime names (the display names could be the same, but the names are not)
Screenshot 2023-04-28 at 2 45 28 PM

6. Add the `add serving runtime` button on the empty page

File: frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx [hunk 6]
```diff
@@ -82,13 +100,21 @@ const CustomServingRuntimeAddTemplate: React.FC<CustomServingRuntimeAddTemplateP
...
                 <Button
-                  isDisabled={code === '' || loading}
+                  isDisabled={code === stringifiedTemplate || code === '' || loading}
                   variant="primary"
                   id="create-button"
                   isLoading={loading}
                   onClick={() => {
                     setIsLoading(true);
-                    createServingRuntimeTemplate(code, dashboardNamespace)
+                    const onClickFunc = existingTemplate
```
Comment (lucferbux) [inline frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx:109]: Nice use of the sintax here 👌

File: frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx [hunk 7]
```diff
@@ -1,60 +1,57 @@
...
-      if (!_.isEqual(newTemplateOrder, templateOrder)) {
-        patchDashboardConfigTemplateOrder(newTemplateOrder, dashboardNamespace)
-          .then(refreshOrder)
-          .catch((e) => notification.error(`Error update the serving runtimes order`, e.message));
-      }
-    },
-    [templateOrder, dashboardNamespace, refreshOrder, notification],
+  const [deleteTemplate, setDeleteTemplate] = React.useState<TemplateKind>();
+  const [dragItemOrder, setDragItemOrder] = React.useState(
+    getDragItemOrder(customServingRuntimes, templateOrder),
```
Comment (lucferbux) [inline frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx:27]: See the comment bellow in `CustomServingRuntimeListView`

**Review by lucferbux — CHANGES_REQUESTED** [review]
My only take here is that I wouldn't use the extra `customServingRuntimes`, everything else seems fine 👌

File: frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx [hunk 8]
```diff
@@ -1,60 +1,56 @@
...
+  const [deleteTemplate, setDeleteTemplate] = React.useState<TemplateKind>();
+  const [dragItemOrder, setDragItemOrder] = React.useState(
+    getDragItemOrder(templates, templateOrder),
   );
 
+  React.useEffect(() => {
+    patchDashboardConfigTemplateOrder(dragItemOrder, dashboardNamespace).catch((e) =>
+      notification.error(`Error update the serving runtimes order`, e.message),
+    );
+  }, [dragItemOrder, dashboardNamespace, refreshOrder, notification]);
```
Comment (lucferbux) [inline frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx:33]: I think we are no longer usin `refreshOrder` anywhere.

**Review by lucferbux — CHANGES_REQUESTED** [review]

File: frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx [hunk 9]
```diff
@@ -1,60 +1,56 @@
...
+        setItemOrder={setDragItemOrder}
         rowRenderer={(template, rowIndex, trDragFunctions) => (
           <CustomServingRuntimeTableRow
             key={template.metadata.uid}
             obj={template}
             rowIndex={rowIndex}
             dragFunctions={trDragFunctions}
+            onDeleteTemplate={(obj) => setDeleteTemplate(obj)}
           />
         )}
```
Comment (lucferbux) [inline frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx:55]:
```suggestion
        rowRenderer={(template, rowIndex, rowId, trDragFunctions) => (
          <CustomServingRuntimeTableRow
            key={template.metadata.uid}
            obj={template}
            rowIndex={rowIndex}
            rowId={rowId || getServingRuntimeNameFromTemplate(template)}
            dragFunctions={trDragFunctions}
            onDeleteTemplate={(obj) => setDeleteTemplate(obj)}
          />
        )}
```

And for this is adapting table, we can either just have flexibility or just giving that for the drag item, iw as thinking about something like this in `Table.tsx`:

` .map((row, rowIndex) => rowRenderer(row, rowIndex, itemOrder[rowIndex], trDragFunctions))}`

**Review by lucferbux — CHANGES_REQUESTED** [review]

**Review by lucferbux — APPROVED** [review]
/lgtm
