### PR TITLE
UI Enhancements

### LINKED ISSUE #802: [Model Serving]: UI Enhancements
### List of tasks

- [x] Inferenceservice loading status icon should be spinner rather than an hourglass.

Screenshot 2022-11-24 at 12 05 48

- [x] Display a tooltip message when the model fails.

Screenshot 2022-11-23 at 16 28 37

- [x] Adding headers to tokens row
- [x] Token sometimes retrieve "Unknown" if secret not properly fetched

Screenshot 2022-11-23 at 16 28 24

- [x] In the "Deploy model" modal, change "Configure" button text to "Deploy" 

Screenshot 2022-11-23 at 16 35 32

- [x] Calculate witdh based on the ? icon -> EDIT, not doing it.

Screenshot 2022-11-23 at 16 53 10

- [x] Route itself doen’t refresh with changes automatically

Screenshot 2022-11-23 at 17 01 29

- [x] HIde the link from the Model names until metrics are enabled

Screenshot 2022-11-24 at 12 13 13

- [x] When inference service is disabled, just change the text to "Internal Service" rather than displaying a route

Screenshot 2022-11-24 at 12 07 41

- [X] Add validation for number inputs
- [X] Change label of "Token Secret" in Model Server modal

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Fix #802
- Inferenceservice loading status icon should be spinner rather than an hourglass.
- Display a tooltip message when the model fails.
- Adding headers to tokens row
- In the "Deploy model" modal, change "Configure" button text to "Deploy"
- Route itself doen’t refresh with changes automatically
- Hide the link from the Model names until metrics are enabled
- When inference service is disabled, just change the text to "Internal Service" rather than displaying a route.

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenDisplay.tsx [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+    return (
+      <HelperText>
+        <HelperTextItem variant="warning" hasIcon>
+          Failed to get token. {error && error.message}
+        </HelperTextItem>
+      </HelperText>
+    );
+  }
+
+  return <ClipboardCopy isReadOnly>{token.data?.token}</ClipboardCopy>;
```
Comment (lucferbux) [inline frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenDisplay.tsx:30]: Missing base64

**Review by lucferbux — COMMENTED** [review]
/hold

File: frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+const InternalServicePopoverContent: React.FC<InternalServicePopoverContentProps> = ({
+  inferenceService,
+}) => {
+  const isInternalServiceEnabled = inferenceService.status?.components?.predictor;
+
+  if (!isInternalServiceEnabled) {
+    return (
+      <Stack hasGutter>
+        <StackItem>Could not find any internal service enabled</StackItem>
+      </Stack>
```
Comment (andrewballantyne) [inline frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx:25]: Huh? What are you guttering?

No harm -- just odd.

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx [hunk 3]
```diff
@@ -16,13 +16,16 @@ const ServingRuntimeReplicaSection: React.FC<ServingRuntimeReplicaSectionProps>
     const target = event.target as HTMLInputElement;
     setData('numReplicas', parseInt(target.value));
   };
+  const validate = data.numReplicas >= 0 ? ValidatedOptions.default : ValidatedOptions.error;
```
Comment (andrewballantyne) [inline frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx:19]: This will never be an error? Your field doesn't allow for negative numbers. In fact, it's min is 1 -- not even 0. I'm confused about this logic.

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenDisplay.tsx [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+}) => {
+  if (!loaded) {
+    return <Skeleton />;
+  }
+
+  if (error || token.data?.token === undefined) {
+    return (
+      <HelperText>
+        <HelperTextItem variant="warning" hasIcon>
+          Failed to get token. {error && error.message}
```
Comment (andrewballantyne) [inline frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenDisplay.tsx:24]: Nit.
```suggestion
          Failed to get token. {error?.message}
```

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx (hunk 3 above)
Comment (andrewballantyne) [reply frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx:19]: Best guess is improper data originally?

**Review by andrewballantyne — APPROVED** [review]
I'm approving this. None of my comments are going to really change anything. I'll talk to you tomorrow about the details if you want.

File: .env [hunk 5]
```diff
@@ -10,9 +10,7 @@
 
 ############### Default settings ###############
 BACKEND_PORT=8080
-IMAGE_REPOSITORY=quay.io/opendatahub/odh-dashboard:dev
-SOURCE_REPOSITORY_URL=git@github.com:opendatahub-io/odh-dashboard.git
-SOURCE_REPOSITORY_REF=master
+IMAGE_REPOSITORY=quay.io/opendatahub/odh-dashboard:nightly
```
[the remark this answers is not in the document]
Comment (lucferbux) [reply .env:13]: Mmmmm, no, this is intended but i mixed up commits, this was targeted for the refactor. We don't use those variables anymore (@LaVLaS changed the deployment scripts and this was used for s2i). And furthermore we don't have a dev tag, we are using the nightly with latest changes.

File: CONTRIBUTING.md [hunk 6]
```diff
@@ -111,9 +111,6 @@ Customize `.env.local` file to image and source information as desired. `npm` an
 
 ```.env.local
 IMAGE_REPOSITORY=quay.io/my-org/odh-dashboard:latest
-SOURCE_REPOSITORY_URL=git@github.com:my-org/odh-dashboard.git
-SOURCE_REPOSITORY_REF=my-branch
-
```
[the remark this answers is not in the document]
Comment (lucferbux) [reply CONTRIBUTING.md:116]: Yes, this was targeted for the revamp, not UI fixes for model serving, my bad.

File: frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx (hunk 2 above)
Comment (lucferbux) [reply frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx:25]: mmmm you are right, i refactored this, first I intended to have more info in the error and then discarded it talking with Vince, might delete it in a follow up.

File: frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts [hunk 7]
```diff
@@ -13,6 +14,11 @@ const useRouteForInferenceService = (
   const routeNamespace = inferenceService.metadata.namespace;
 
   React.useEffect(() => {
+    if (!isRouteEnabled) {
```
[the remark this answers is not in the document]
Comment (lucferbux) [reply frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts:17]: Yup that's right, this is targeted to present the skeleton when there are new changes, if not, the old content would be present until updated with no visual cue.

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx (hunk 3 above)
Comment (lucferbux) [reply frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx:19]: No, this is targeted for when the user input the fields manually, not using the counter buttons. This  was a feedback from QE, you can trigger an empty value/0 as an input field.

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenDisplay.tsx (hunk 4 above)
Comment (lucferbux) [reply frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenDisplay.tsx:24]: Rigth, changing it in a follow up.

**Comment by lucferbux** [comment]
> I'm approving this. None of my comments are going to really change anything. I'll talk to you tomorrow about the details if you want.
Nice, thanks for the feedback, opening a follow up

File: frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx (hunk 3 above)
Comment (andrewballantyne) [reply frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx:19]: Sounds like you need smarter onChange logic... I thought the number input just brought it back to the min value -- if you can actually input anything, it's not a valid value and it should snap back to `min`.

Showing something wrong serves nobody -- unless you can think of a flow a user can do that starts invalid and goes to valid... something like 1.2 "1" valid, "1." invalid, "1.2" valid. But I'm not sure that is the case here. Letting them type "abc" in a field intended for a number is weird.

Comment (lucferbux) [reply frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx:19]: Mmmm yeah, I am not happy with the result either, I tried first adding more logic for the onChange handler but I bumped into some issues too. I'm gonna create an issue to cover this specific logic. Thanks again.
