### PR TITLE
Fix a11y errors in DSP screens

### LINKED ISSUE #1104: [A11y] Address A11y issues in Data Science Projects
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Various: [RHODS-6426](https://issues.redhat.com/browse/RHODS-6426)
- VO not reading form label of number input field in “Configure model server” modal: [RHODS-6973](https://issues.redhat.com/browse/RHODS-6973)
- Help icons not VO accessible and need aria-labels: [RHODS-6974](https://issues.redhat.com/browse/RHODS-6974)
- Table header text should not be empty: [RHODS-6433](https://issues.redhat.com/browse/RHODS-6433)

### PR DESCRIPTION
**Pull request by jenny-s51**
Closes #1104 

## Description

Fixed a11y violations in DSP screens, see JIRA tickets in #1104. Attached screenshots below. Remaining changes were tested with VO.

## How Has This Been Tested?

DSP list before:
Screenshot 2023-04-13 at 3 51 49 PM

DSP list after:
Screenshot 2023-04-13 at 3 51 56 PM

Create workbench before:
Screenshot 2023-04-12 at 3 00 57 PM
Screenshot 2023-04-12 at 3 15 40 PM

Create workbench after:
Screenshot 2023-04-12 at 3 00 24 PM
Screenshot 2023-04-12 at 3 15 47 PM

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

File: frontend/src/components/Table.tsx [hunk 1]
```diff
@@ -84,15 +85,19 @@ const Table = <T,>({
...
+              col.label ? (
+                <Th
+                  key={col.field + i}
+                  sort={col.sortable ? sort.getColumnSort(i) : undefined}
+                  width={col.width}
+                >
+                  {col.label}
+                </Th>
+              ) : (
+                <Td key={col.field + i} width={col.width} />
```
Comment (DaoDaoNoCode) [inline frontend/src/components/Table.tsx:98]: Why it's `Td` here but not `Th`?

File: frontend/src/pages/notebookController/NotebookController.scss [hunk 2]
```diff
@@ -56,6 +56,9 @@
         white-space: nowrap;
       }
     }
+    &-popover-help-icon {
```
Comment (DaoDaoNoCode) [inline frontend/src/pages/notebookController/NotebookController.scss:59]: We should avoid creating more custom CSS styles. I have attached the possible solution to avoid using `Button`.

File: frontend/src/pages/notebookController/screens/server/ImageTagPopover.tsx [hunk 3]
```diff
@@ -35,7 +35,14 @@ const ImageTagPopover: React.FC<ImageTagPopoverProps> = ({ tag, description }) =
         </>
       }
     >
-      <OutlinedQuestionCircleIcon />
+      <Button
```
Comment (DaoDaoNoCode) [inline frontend/src/pages/notebookController/screens/server/ImageTagPopover.tsx:38]: I know `Button` could create some paddings which will break the layout so you need to add custom CSS to override it. We can also consider the `Icon` component.
Maybe we can do the following:
```
<Icon aria-label="More info" role="button" tabIndex={0}>
<OutlinedQuestionCircleIcon />
</Icon>
```
I tested this on PF examples and it works for VO.

File: frontend/src/pages/projects/components/ResourceNameTooltip.tsx [hunk 4]
```diff
@@ -46,7 +48,14 @@ const ResourceNameTooltip: React.FC<ResourceNameTooltipProps> = ({ children, res
             </Stack>
           }
         >
-          <OutlinedQuestionCircleIcon />
+          <Button
```
Comment (DaoDaoNoCode) [inline frontend/src/pages/projects/components/ResourceNameTooltip.tsx:51]: Same here, maybe use `Icon` instead.

**Review by DaoDaoNoCode — COMMENTED** [review]
Left some comments, let me know if the layout is broken after you apply the changes as suggested in the comments!

File: frontend/src/components/Table.tsx (hunk 1 above)
Comment (jenny-s51) [reply frontend/src/components/Table.tsx:98]: @DaoDaoNoCode `Th` cells cannot be empty. In certain tables we have an actions column, so the [PF recommendation is to use `Td`](https://www.patternfly.org/v4/components/table#composable-actions) there.

File: frontend/src/pages/notebookController/screens/server/ImageTagPopover.tsx (hunk 3 above)
Comment (jenny-s51) [reply frontend/src/pages/notebookController/screens/server/ImageTagPopover.tsx]: Thanks @DaoDaoNoCode - great idea

**Review by DaoDaoNoCode — APPROVED** [review]
lgtm, thanks!

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by andrewballantyne** [comment]
Double reviewed by the devs, adding Approved label without investigating.
