### PR TITLE
Type check when notebookController is not defined

### LINKED ISSUE #453: [Bug]: Dashboard will crash when `notebookController` and `enabled` is not presented in dashboard config
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the dashboard will get 500 errors when getting enabled components if
```
notebookController:
  enabled: true
```
is not present.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Workaround (if any)

_No response_

### OpenShift Infrastructure Version

_No response_

### Openshift Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
## Description

Closes #453 

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: backend/src/utils/componentUtils.ts [hunk 1]
```diff
@@ -278,3 +283,6 @@ export const convertLabelsToString = (labels: { [key: string]: string }): string
   }
   return outputString;
 };
+
+export const getIsJupyterEnabled = (): boolean | undefined =>
+  getDashboardConfig().spec.notebookController?.enabled;
```
Comment (andrewballantyne) [inline backend/src/utils/componentUtils.ts:288]: A boolean based function should always return a boolean value unless you think `undefined` can be something special. Please convert the value to a boolean before returning and make this function just return a boolean.

**Review by andrewballantyne — APPROVED** [review]
Works, JH appears when we do not have KFNBC settings available.
