### PR TITLE
Fix issue when doing first migration of Serving Runtime enablement

### LINKED ISSUE #1562: [Bug]: Backend returning wrong dashboard config
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

There's an edge condition in which clusters with old serving runtime configuration were returning a misconfigured `OdhDashboardConfig` without the `status` attribute, which is required, so the first time it won't return the correct dashboard configuration.

### Expected Behavior

To return the `status` attribute in `OdhDashboardConfig` object in the `status` endpoint.

### Steps To Reproduce

1. Get the annotation `opendatahub.io/template-enabled` one one of the templates.
2. Reload the dashboard pod
3. Check that the first `status` object doesn't return `status` in DashboardConfig

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Anything else

It won't break anything, but we should avoid this kind of scenearios

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Closes #1562 

## How Has This Been Tested?

1. Get the annotation opendatahub.io/template-enabled one one of the templates.
2. Reload the dashboard pod
3. Check that the first status object doesn't return status in DashboardConfig

## Test Impact

No testing coverage added to backend, no planned efforts for that component

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: backend/src/utils/resourceUtils.ts [hunk 1]
```diff
@@ -807,8 +807,10 @@ export const migrateTemplateDisablement = async (
             undefined,
             options,
           )
-          .then((response) => {
-            return response.body as DashboardConfig;
+          .then(() => {
+            return _.merge({}, dashboardConfig, {
+              templateDisablement: templatesDisabled,
+            });
```
Comment (christianvogt) [inline backend/src/utils/resourceUtils.ts:813]: `templateDisablement` should be assigned as a property of `spec` and not on the root of the config object.

Comment (christianvogt) [reply backend/src/utils/resourceUtils.ts:813]: `merge` results in a new type that still conforms to `DashboardConfig`. I suggest first cloning the object and then doing an assignment. 
If you provide some type arguments to `merge`, you'll see the type error that is otherwise hidden. eg:
`_.merge<Partial<DashboardConfig>, DashboardConfig, Partial<DashboardConfig>>(...)`

Comment (lucferbux) [reply backend/src/utils/resourceUtils.ts:813]: @christianvogt You are absolutely right, but I needed to retest it, not sure how but lodash was successfully merging the object here, not sure how that was happening o.O

**Review by DaoDaoNoCode — APPROVED** [review]
lgtm
