### PR TITLE
Correctly render divider between sections on project details page

### LINKED ISSUE #1032: [Bug]: Project Details - Dynamically Add Divider Bar on empty state
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now our empty state + divider is very non uniform.

If you enable features, disable features and in general had 3, 4, or 5 sections -- there is no way to know which is the last today from each section. So no way to know if you need to add a divider bar.

Now this would be simple if the divider bar was between each section if it had data or not -- the page render could do that. But since it's only on empty state it needs to feed this information into each section so they can decide based on their empty state.

### Expected Behavior

Each section in empty state to have the appropriate divider line at the bottom.

- Last one does not get it
- Data filled sections do not get it

### Steps To Reproduce

1. Create a project

Play with the disabled sections. Right now there is only Model Serving -- but soon Pipelines will be here and it'll just increase in uncertainty. 

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
Dashboard: v2.8.0
```

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Close #1032 

## Description

Instead of adding the Divider by providing a prop named `includeDivider` in `EmptyDetailsList` component, I moved the divider to the render of the page. In each section, I added a prop named `isEmpty` to check whether the section is empty or not based on the context provider, then only render the divider below the section when the section is empty and it's not the last section on the page.

### Screenshots:
1. Before:
Screenshot 2023-03-27 at 2 27 06 PM

2. After the change, when all the sections are empty:
Screenshot 2023-03-27 at 4 26 06 PM

3. After the change, when the model serving feature is disabled (so the data connection is the last section):
Screenshot 2023-03-27 at 4 32 42 PM

4. After the change, when some sections are not empty:
Screenshot 2023-03-27 at 4 33 36 PM
Screenshot 2023-03-27 at 4 34 08 PM

Visual changes cc @kywalker-rh

## How Has This Been Tested?

1. Create a project, and check the dividers between the sections
2. Try to create and delete workbenches/storages/data connections... see if there are dividers. The correct result should be there are no dividers between sections when the top section is not empty and there is no divider at the bottom in any situation.
3. Try to disable the model serving feature by changing the dashboard config so the data connections section is the last one, and make sure you cannot see the divider under it no matter if there are data connections in the section or not.

## Test Impact

Add storybook test for project details page, check no dividers on default page (with data) and ${section number minus one} dividers on an empty page.

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

File: frontend/src/pages/projects/screens/detail/ProjectDetails.tsx [hunk 1]
```diff
@@ -71,10 +103,13 @@ const ProjectDetails: React.FC = () => {
...
-              <StackItem key={id} id={id} aria-label={ProjectSectionTitles[id]}>
-                {component}
-              </StackItem>
+            {sections.map(({ id, component, isEmpty }, index) => (
+              <>
+                <StackItem key={id} id={id} aria-label={ProjectSectionTitles[id]}>
+                  {component}
+                </StackItem>
+                {index !== sections.length - 1 && isEmpty && <Divider />}
+              </>
```
Comment (lucferbux) [inline frontend/src/pages/projects/screens/detail/ProjectDetails.tsx:112]:
```suggestion
              <React.Fragment key={id}>
                <StackItem id={id} aria-label={ProjectSectionTitles[id]}>
                  {component}
                </StackItem>
                {index !== sections.length - 1 && isEmpty && <Divider />}
              </React.Fragment>
```

You should have the key at top of the fragment, if not react will not handle the rendering element key.

**Review by lucferbux — CHANGES_REQUESTED** [review]

File: frontend/src/__mocks__/mockPVCK8sResource.ts [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+      'pv.kubernetes.io/bound-by-controller': 'yes',
+      'volume.beta.kubernetes.io/storage-provisioner': 'ebs.csi.aws.com',
+      'volume.kubernetes.io/selected-node': 'ip-10-0-133-119.us-west-2.compute.internal',
+      'volume.kubernetes.io/storage-provisioner': 'ebs.csi.aws.com',
+    },
+    resourceVersion: '864084751',
+    name,
+    uid: '8644e33b-a710-45a3-9d54-7f987494643a',
+    creationTimestamp: '2023-03-03T03:17:32Z',
+    managedFields: [
```
Comment (lucferbux) [inline frontend/src/__mocks__/mockPVCK8sResource.ts:30]: Just a nit pick, do we need managedFields for mocks? It's not bad, but it's an internal resource that I think it has no value for us, just curious what the rest think about it @andrewballantyne @alexcreasy @Gkrumbach07

File: frontend/src/__mocks__/mockServingRuntimesConfig.ts [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+    uid: 'e581ed91-f36d-4826-85cf-2526c61028b3',
+    resourceVersion: '801334675',
+    creationTimestamp: '2022-09-16T17:02:55Z',
+    labels: {
+      app: 'odh-dashboard',
+      'app.kubernetes.io/part-of': 'odh-dashboard',
+    },
+    annotations: {
+      'kfctl.kubeflow.io/kfdef-instance': 'odh-core.odh',
+      'kubectl.kubernetes.io/last-applied-configuration':
```
Comment (lucferbux) [inline frontend/src/__mocks__/mockServingRuntimesConfig.ts:26]: Same with last-applied-configuration, seems a little weird for me, but it's not bad.

**Review by lucferbux — APPROVED** [review]
I'm approving it cause my two comments are more questions rather than change requests and they don't affect to the feature itself. Tested and it seems to be working great.

File: frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+  parameters: {
+    reactRouter: {
+      routePath: '/projects/:namespace/*',
+      routeParams: { namespace: 'test-project' },
+    },
+    msw: {
+      handlers: handlers(false),
+    },
+  },
+} as ComponentMeta<typeof ProjectDetails>;
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx:76]: @Gkrumbach07 `as` is very not ideal. We need to consider better templating and direction to avoid this as a requirement for the default export.

File: frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+
+const Template: ComponentStory<typeof ProjectDetails> = (args) => {
+  useDetectUser();
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx:79]: 🤔 This probably should be at the top of the test infra.

cc @Gkrumbach07

**Review by andrewballantyne — COMMENTED** [review]
Couple testing questions -- let me test the PR.

**Review by andrewballantyne — APPROVED** [review]
Looks great! Thanks for cleaning this up -- Pipelines will be very happy 😄

**Review by andrewballantyne — APPROVED** [review]
Cleanup of the mocks look good. Thanks!

File: frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx (hunk 4 above)
Comment (Gkrumbach07) [reply frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx:76]: I believe it is required by storybook for the default export to be that? I might be confused on what you are asking?

File: frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx (hunk 5 above)
Comment (Gkrumbach07) [reply frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx:79]: Yes, it should. I think we can add it to the top at preview.js. We put it here just to get it working quickly without having to figure out how to get it working at the top level. The issue is that that hook requires the context provider to be  above it. we can add it to the global decorator, but that would sit above it. We could create a component just for and place the hook in there and put that under the provider, but that seems like a lot.

Comment (Gkrumbach07) [reply frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx:79]: However, the decorators is an array. so we should be able to just add another below it

File: frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx (hunk 4 above)
Comment (andrewballantyne) [reply frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx:76]: `as` is never required. As tells TS to override it's thinking. You're trying to solve a type problem by "forcing" TS to be a type. It's not ideal. We should type things with normal types and then export them.

Eg.
```
const baseSettings: TheTypeYouWant = {
   ...
}
export default baseSettings;
```

File: frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx (hunk 5 above)
Comment (andrewballantyne) [reply frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx:79]: Gotcha -- so you'll follow up with another issue?

Comment (DaoDaoNoCode) [reply frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx:79]: I think the best way is to follow up this in another issue because we need to mock up the object that returns from the `status` endpoint.
