### PR TITLE
Remove projects filter on the project view page

### LINKED ISSUE #2120: [Bug]: Data science projects search filter dropdown has meaningless field
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

main

### Current Behavior

In the search of the projects, we should only have 2 fields `Name` and `User`, there is no `Project` search field. Also, we should look into replacing the search field with the generic one we are using `DashboardSearchField`.

Screenshot 2023-11-10 at 11 17 23 AM

### Expected Behavior

Should only have 2 dropdown items for searching: `Name` and `User`

### Steps To Reproduce

1. Go to the data science projects page
2. Toggle the search dropdown
3. You will see the bug, and when you search for `Project` you will never filter out anything because this field shouldn't be there

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #2120 

## Description

One liner. Just filter the search types.

Screenshot 2023-11-15 at 11 48 40 AM

## How Has This Been Tested?

1. Go to the data science projects page
2. Check the search filter, make sure there are only `Name` and `User` could be selected
3. Verify they are working

## Test Impact

Update the test cases a little bit to verify the filter dropdowns.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: frontend/src/pages/projects/screens/projects/ProjectListView.tsx [hunk 1]
```diff
@@ -47,7 +47,7 @@ const ProjectListView: React.FC<ProjectListViewProps> = ({ allowCreate, scope })
     setSearch('');
   };
 
-  const searchTypes = React.useMemo(() => Object.values(SearchType), []);
+  const searchTypes = React.useMemo(() => [SearchType.NAME, SearchType.USER], []);
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/projects/ProjectListView.tsx:50]: Why? Remove the unused value from the SearchType enum?

File: frontend/src/__tests__/integration/pages/projects/ProjectView.spec.ts [hunk 2]
```diff
@@ -26,6 +24,10 @@ test('Project view page', async ({ page }) => {
   await expect(page.getByText('Non-DS Project 1', { exact: true })).toBeVisible();
   await expect(page.getByText('Non-DS Project 2', { exact: true })).toBeVisible();
   await expect(page.getByText('Non-DS Project 3', { exact: true })).toBeVisible();
+
+  await page.locator('#search-field-toggle').click();
+  await expect(page.getByRole('listitem').first()).toHaveText('Name');
+  await expect(page.getByRole('listitem').last()).toHaveText('User');
```
Comment (andrewballantyne) [inline frontend/src/__tests__/integration/pages/projects/ProjectView.spec.ts:30]: Yay Tests! didn't even consider that. Can we also make a test to say has only 2 options? Seems weird to check only first/last... there could be one in the middle.

File: frontend/src/pages/projects/screens/projects/ProjectListView.tsx (hunk 1 above)
Comment (DaoDaoNoCode) [reply frontend/src/pages/projects/screens/projects/ProjectListView.tsx:50]: Hmm, because I found that the `SearchType` is also used in `InferenceServiceListView`, where they need `SearchType.PROJECT`...

Comment (DaoDaoNoCode) [reply frontend/src/pages/projects/screens/projects/ProjectListView.tsx]: @andrewballantyne OK, so I decided to change `InferenceServiceListView` to use the weird generic `DashboardSearchField` for now to make this project search field pure. We can change the use of `DashboardSearchField` in the future.

Comment (andrewballantyne) [reply frontend/src/pages/projects/screens/projects/ProjectListView.tsx]: I don't think you should have done that... that bloats this. We are talking enums here -- why are we not just making an enum for each page instead of some bastardized combination that needs to now know of what another page is doing in order to operate. Maybe we should talk about the foot print of this work.

File: frontend/src/__tests__/integration/pages/projects/ProjectView.spec.ts [hunk 3]
```diff
@@ -26,6 +24,9 @@ test('Project view page', async ({ page }) => {
   await expect(page.getByText('Non-DS Project 1', { exact: true })).toBeVisible();
   await expect(page.getByText('Non-DS Project 2', { exact: true })).toBeVisible();
   await expect(page.getByText('Non-DS Project 3', { exact: true })).toBeVisible();
+
+  await page.locator('#search-field-toggle').click();
+  await expect(page.getByRole('listitem')).toHaveCount(2);
```
Comment (andrewballantyne) [inline frontend/src/__tests__/integration/pages/projects/ProjectView.spec.ts:29]: Uh, meant both check 0 & 1 as intended values but ALSO check the length -- and not just trust they are first and last is what we want... that seems like a half-test. Like this is currently.

File: frontend/src/pages/projects/screens/projects/ProjectListView.tsx (hunk 1 above)
Comment (andrewballantyne) [reply frontend/src/pages/projects/screens/projects/ProjectListView.tsx]: This is fine, talked with Juntao. Will test and see if it works as intended.

**Review by andrewballantyne — APPROVED** [review]
