### PR TITLE
Select connected notebooks when creating and editing data connections

### LINKED ISSUE #787: [Bug]: Align DSG Connection Modals
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now when you create a Data Connection you can't assign it right away to a modal. You'll need to connect it after the fact.

### Expected Behavior

Align our Storage and Data Connections modals to have similar structure as per UX: https://www.sketch.com/s/2ca3f24d-2814-47ab-bcba-697c742538ed/a/25jaOxy.

### Steps To Reproduce

View creation & edit modals. They should be able to modify connections.

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
2.4.0
```

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
## Description

Closes #787 

## How Has This Been Tested?

Go to data connections list, try to create data connections or edit data connections, you will be able to select the connected workbench at the same time.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: frontend/src/pages/projects/notebook/utils.ts [hunk 1]
```diff
@@ -252,3 +252,6 @@ export const useNotebookStatus = (
 
 export const getEventFullMessage = (event: EventKind): string =>
   `${getEventTimestamp(event)} [${event.type}] ${event.message}`;
+
+export const getNotebooksNames = (notebooks: NotebookKind[]): string[] =>
+  notebooks.map((notebook) => notebook.metadata.name);
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/notebook/utils.ts:257]: huh? Just do this where you need it? It's not custom logic, it's just working with k8s objects. If anything we can getResourceName in our base utils for projects -- but it seems kinda goofy

File: frontend/src/pages/projects/notebook/useRelatedNotebooks.ts [hunk 2]
```diff
@@ -25,6 +25,18 @@ const useRelatedNotebooks = (
   } = React.useContext(ProjectDetailsContext);
 
   const connectedNotebooks = React.useMemo(() => {
+    if (context === ConnectedNotebookContext.POSSIBLE_DATA_CONNECTION) {
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/notebook/useRelatedNotebooks.ts:28]: I don't like lol -- this belongs in the switch statement... maybe we inline the escape early for no resource name for the other calls? 🤔 

I want to keep the switch statement full for each case.

File: frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx [hunk 3]
```diff
@@ -53,27 +72,62 @@ const ManageDataConnectionModal: React.FC<ManageDataConnectionModalProps> = ({
...
-        .then(() => onBeforeClose(true))
-        .catch(handleError);
+      if (AWSDataChanged) {
+        promiseActions.push(replaceSecret(assembledSecret));
+      }
+
+      const notebooksToDisconnect = allAvailableNotebooks.filter((notebook) =>
+        removedConnections.includes(notebook.metadata.name),
+      );
+      notebooksToDisconnect.forEach((notebook) => {
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx:86]: Nit. `promiseActions.push(...notebooksToDisconnect.map(...));`

File: frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx [hunk 4]
```diff
@@ -53,27 +72,62 @@ const ManageDataConnectionModal: React.FC<ManageDataConnectionModalProps> = ({
...
-        })
-        .catch(handleError);
+      promiseActions.push(createSecret(assembledSecret));
+    }
+
+    const notebooksToConnect = allAvailableNotebooks.filter((notebook) =>
+      addedConnections.includes(notebook.metadata.name),
+    );
+
+    notebooksToConnect.forEach((notebook) =>
```
Comment (andrewballantyne) [inline frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx:107]: Same comment here too... I just find `.forEach` usages should not push into an array, they should be used for side-effects.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
Code comments, testing now

**Comment by andrewballantyne** [comment]
Works well though.

/approve

Just need those code comments addressed and we should be good to go.

File: frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx (hunk 3 above)
Comment (andrewballantyne) [reply frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx:86]: FWIW, alternative is to use `.reduce` and the initial data is the array.

`notebooksToDisconnect.reduce((promises, notebook) => ([...promises, some_logic], promiseActions)`

**Review by andrewballantyne — APPROVED** [review]
/unhold

**Comment by andrewballantyne** [comment]
/hold

Testing again and seeing weird things... sec

**Review by andrewballantyne — APPROVED** [review]
/unhold
