### PR TITLE
Fix hardcoded PVC size

### LINKED ISSUE #341: [KFNBC]: Do not hardcode PVC size
### Description

Get PVC size from OdhDashboardConfiguration CRD instead of hardcoding it:

https://github.com/opendatahub-io/odh-dashboard/blob/56149975eff9047dab3a77503f313153d27e4ba0/frontend/src/pages/notebookController/SpawnerPage.tsx#L303

### PR DESCRIPTION
**Pull request by mlassak**
Resolves #341

Adds ```pvcSize``` attribute to ```notebookController``` and utilizes it to replace the hardcoded PVC size value.

### CODE REVIEW

File: frontend/src/pages/notebookController/SpawnerPage.tsx [hunk 1]
```diff
@@ -300,7 +300,9 @@ const SpawnerPage: React.FC<SpawnerPageProps> = React.memo(({ setStartModalShown
       const pvcName = generatePvcNameFromUsername(username);
       const pvc = await getPvc(pvcName);
       if (!pvc) {
-        await createPvc(pvcName, '20Gi');
+        const defaultPvcSize = '20Gi';
```
Comment (DaoDaoNoCode) [inline frontend/src/pages/notebookController/SpawnerPage.tsx:303]: Instead of defining the default PVC size here every time, could you move it to const.ts like `DEFAULT_PVC_SIZE` and import it to this file?

**Review by DaoDaoNoCode — CHANGES_REQUESTED** [review]
Overall it LGTM, leave a small comment.
BTW, can you also update the doc here to add `pvcSize` field? https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/dashboard_config.md#notebook-controller

File: backend/src/routes/api/status/statusUtils.ts [hunk 2]
```diff
@@ -20,7 +20,7 @@ export const status = async (
   const { currentContext, namespace, currentUser, clusterID, clusterBranding } = fastify.kube;
   const customObjectsApi = fastify.kube.customObjectsApi;
   const coreV1Api = fastify.kube.coreV1Api;
-  const rbacAuthorizationApi = fastify.kube.rbac;
+  const rbacAuthorizationApi = fastify.kube.rbac; // eslint-disable-line
```
Comment (andrewballantyne) [inline backend/src/routes/api/status/statusUtils.ts:23]: remove the line if it's not used.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
I agree with Juntao, a new constant in the constants file is more preferred than inline. Keeps everything together. One could make an argument to be part of the blankDashboardConfig but I do not think it is needed -- we'd still need to handle the default.

**Comment by andrewballantyne** [comment]
@mlassak any reason this is a DRAFT PR?

File: frontend/src/pages/notebookController/SpawnerPage.tsx [hunk 3]
```diff
@@ -300,7 +300,9 @@ const SpawnerPage: React.FC<SpawnerPageProps> = React.memo(({ setStartModalShown
...
+        const requestedPvcSize = dashboardConfig?.spec?.notebookController?.pvcSize;
+        await createPvc(pvcName, requestedPvcSize ?? defaultPvcSize);
```
[the remark this answers is not in the document]
Comment (DaoDaoNoCode) [reply frontend/src/pages/notebookController/SpawnerPage.tsx:305]: Yeah I think I already refactor this part in my PR here https://github.com/opendatahub-io/odh-dashboard/pull/331/files#diff-9415e5a981134b74b9e1a0fa3a0084ec2fabb9ca5cc0dbd0b98e03c5a009d65dR302-R304

**Comment by maroroman** [comment]
> @mlassak any reason this is a DRAFT PR?

Sorry, this one is on me. There was previously a workflow such that we created a draft PR first so we can share the changes easily for other colleagues. This Pr was not meant to be reviewed yet, I just told Marek to post it so I could check it out.

**Comment by maroroman** [comment]
https://github.com/opendatahub-io/odh-dashboard/pull/269 Adds a condition checking for notebook controller being enabled, since it would be duplicate code, me and @mlassak decided to rebase on top of that PR to use those changes in this PR. The backend will include using the pvcSize in the dashboard CR only if the notebook controller is enabled, otherwise it will set the pvcsize value in the jupyterhub-cfg configmap.

**Comment by maroroman** [comment]
@samuelvl while testing this feature I noticed I had to delete the PVC and PV (or create a notebook for the first time in the cluster)) to get a different volume size, do we fix this behavior in this PR?

**Comment by samuelvl** [comment]
@maroroman The volume size only applies for the first time the PVC is created

**Comment by maroroman** [comment]
> @samuelvl while testing this feature I noticed I had to delete the PVC and PV (or create a notebook for the first time in the cluster) to get a different volume size, do we fix this behavior in this PR?

After an offline discussion, the current behavior is correct.

**Review by maroroman — APPROVED** [review]
lgtm

**Review by DaoDaoNoCode — APPROVED** [review]
lgtm

**Review by andrewballantyne — APPROVED** [review]
Approving to undo my requested changes -- I have not reviewed the updated changes but it appears we have enough other approvals to merge.
