### PR TITLE
Delete pipeline server from the Pipelines Section in Projects page

### LINKED ISSUE #1542: [Bug]: No way to delete a Pipeline Server in DS Projects
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

I can create a Pipeline Server:

Screenshot 2023-07-19 at 13 13 11

But I can't find any way to modify it or delete it after. 

But I should be able to delete, potentially to re-create it after? 

This is all I see:

Screenshot 2023-07-19 at 13 13 24

This can be performed in the Pipeline section, but not in DS projects:

Screenshot 2023-07-19 at 13 17 06

### Expected Behavior

Have the ability to delete a Pipeline Server

### Steps To Reproduce

1. Create a Pipeline Server
2. Try to delete it in DS Projects

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by manaswinidas**
Fixes #1542 

## Description

We can now delete pipeline server from the Pipelines Section in Projects page. Reused `PipelinesPageHeaderActions`.The functionality is the same as `Pipeline Server Actions` dropdown in Global Pipelines page, only the toggle is `KebabToggle`.

More details: #1542 
The design has been provided in #1542 

Edit - @kywalker-rh implemented the design provided in #1542 Also, what do we do if pipeline server is not installed? Currently, the "Import pipeline" button is disabled when there is no pipeline server. Do I disable this menu or hide it altogether? I'm hiding it currently. You can check the screenshots below for all states:

Edit 1: Disabling both the kebab menu on Projects page and the "Pipeline Server Actions" button in Global Pipelines page when there is no pipeline server (https://github.com/opendatahub-io/odh-dashboard/pull/1743#issuecomment-1711878609)
 
With pipeline server installed:

Screenshot 2023-09-05 at 5 35 10 PM

With no pipeline server - Projects page(Disabled kebab menu beside "Import Pipeline" button):

Screenshot 2023-09-11 at 11 31 43 PM

With no pipeline server - Global Pipelines page(Disabled "Pipelines Server Actions" button on the top-right):

Screenshot 2023-09-11 at 11 32 03 PM

Tooltips when there is no pipeline server:

Global Pipelines page:

Screenshot 2023-09-26 at 10 37 14 PM

Projects page:
Screenshot 2023-09-26 at 10 36 59 PM

## How Has This Been Tested?

1. Go to Projects page and scroll/navigate to the Pipelines section 
2. Check whether you can see the kebab menu in the Pipelines Section(you should only see the enabled kebab menu icon when you have a pipeline server installed and/or the pipeline is in an initializing state, and in a disabled state when there is no pipeline server) and check the functionality of each dropdown item. Check whether you can see the tooltip when the kebab menu is disabled. 
3. Go to Global Pipelines page and check whether you see the "Pipeline Server Actions" dropdown in the header page and check the functionality of dropdown items. This will be disabled when there is no Pipeline server. You can see the tooltip when there is no Pipeline Server.

## Test Impact

TBD

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [X] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx [hunk 1]
```diff
@@ -1,21 +1,32 @@
...
+import { Dropdown, DropdownItem, DropdownSeparator, MenuToggle } from '@patternfly/react-core';
 import { DeleteServerModal, ViewServerModal } from '~/concepts/pipelines/context';
 
-const PipelinesPageHeaderActions: React.FC = () => {
+type PipelinesPageHeaderActionsProps = {
+  toggleElement: React.ReactNode;
+  variant: 'plain' | 'secondary';
+};
+
+const PipelinesPageHeaderActions: React.FC<PipelinesPageHeaderActionsProps> = ({
```
Comment (manaswinidas) [inline frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:10]: Should we still use the name `PipelinesPageHeaderActions` now that it is being used in the `PipelinesSection` page too?

File: frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx [hunk 2]
```diff
@@ -23,6 +25,11 @@ const PipelinesSection: React.FC = () => {
           key={`action-${ProjectSectionID.PIPELINES}`}
           variant="secondary"
         />,
+        <PipelinesPageHeaderActions
+          key={`action-${ProjectSectionID.PIPELINES}`}
```
Comment (manaswinidas) [inline frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx:29]: I'm aware that the `key` should be unique. Any naming conventions that we follow?

**Comment by manaswinidas** [comment]
Also, is the base branch fine? There is some discussion in https://github.com/opendatahub-io/odh-dashboard/issues/1542#issuecomment-1642644859 to convert this into a feature.

**Comment by pnaik1** [comment]
@manaswinidas can you please take a look at last row of self checklist  and also tag UX?

**Comment by manaswinidas** [comment]
@pnaik1 the design is already provided by UX in the issue. I practically implemented the same.

**Comment by kywalker-rh** [comment]
@manaswinidas I would keep the kebab menu (ellipsis) but disable it if there is no pipeline server.
cc: @yannnz

**Comment by manaswinidas** [comment]
@kywalker-rh won't this be incohesive with the `Pipeline server actions` dropdown in the "Global Pipelines Page" if we disable it? We don't see a `Pipeline server actions` when there's no pipeline server in the "Global Pipelines Page" now when there's no pipeline server. 
Current behavior(Global Pipelines page) when there's no pipeline server- the "Pipeline Server actions" dropdown is hidden:

Screenshot 2023-09-07 at 2 28 34 AM

vs When there's a pipeline server - the dropdown is visible on the top right:

Screenshot 2023-09-07 at 2 27 54 AM

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 1 above)
Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:10]: A better name IMO can be `PipelineServerActions` (same as the name in the header dropdown on the "Global Pipelines Page").

**Comment by kywalker-rh** [comment]
@manaswinidas That's a good question. With this context I actually think we should show, but disable, the button on the full pipelines page as well. So both the kebab in the Project view page and the "Pipeline server actions" button on the Pipelines page would be visible, but disabled before the user creates the Pipeline server.

**Comment by manaswinidas** [comment]
@kywalker-rh If we just disable, it's highly likely that users will try to click or at least hover over them. If we disable them, then we need to provide tooltips too. Wdyt?

**Comment by kywalker-rh** [comment]
Sure, let's use the same tooltip for both, "To access the pipeline server actions, first create a pipeline server."

**Comment by manaswinidas** [comment]
@kywalker-rh Updated as per your suggestions. Please refer to the PR description for screenshots.

**Comment by kywalker-rh** [comment]
Thanks @manaswinidas, this looks good!

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx [hunk 3]
```diff
@@ -1,39 +1,72 @@
...
-          </DropdownItem>,
-        ]}
-      />
+        position="bottom"
+      >
+        <Dropdown
+          removeFindDomNode
+          onSelect={() => setOpen(false)}
+          toggle={
+            <MenuToggle
```
Comment (christianvogt) [inline frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:43]: Use `DropdownToggle` because keyboard navigation to the menu items does not work when you mix `Dropdown` with `MenuToggle`.

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx [hunk 4]
```diff
@@ -1,39 +1,72 @@
...
+              aria-label="header-actions-toggle"
```
Comment (christianvogt) [inline frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:44]: This is not a good readable aria label. You need the label for the kebab but not for the text button. Doesn't hurt to be redundant though. May as well set it to `Pipeline Server Actions`

**Review by christianvogt — COMMENTED** [review]
The tooltip interferes with the dropdown menu as I hover any of the actions:
image

Same goes for the actions in the pipelines page. Here I'd say that the tooltip, even if not overlapping, doesn't add value because the button already reads `Pipeline server actions`.
image

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 3 above)
Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:43]: I've replaced the `DropdownToggle` with `MenuToggle` as I'm reusing the `PipelinePageHeaderActions` to render both a Dropdown and a Kebab(as per https://www.patternfly.org/components/menus/dropdown#with-kebab-toggle) as both the menus contain the same dropdown items.

If I use `DropdownToggle`, the kebab menu looks something like this:
Screenshot 2023-09-13 at 6 47 02 PM

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx [hunk 5]
```diff
@@ -1,39 +1,76 @@
...
+      {isDisabled ? (
+        <Tooltip
+          content="To access the pipeline server actions, first create a pipeline server."
+          position="bottom"
+        >
+          {DropdownComponent}
+        </Tooltip>
+      ) : (
+        { DropdownComponent }
+      )}
```
Comment (manaswinidas) [inline frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:73]: I had thought of modifying the z-index of the tooltip to hide it when `isDisabled` is `false` coz there is no tooltip content when `isDisabled` is `false`. Not sure if that's better.

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 3 above)
Comment (christianvogt) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: @manaswinidas I think PF5 has much better support for `Menu`. In PF4 a [dropdown with a kebab](http://v4-archive.patternfly.org/v4/components/dropdown#kebab-toggle) uses `KebabToggle`.

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 5 above)
Comment (christianvogt) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:73]: Why not open the tooltip to the right and omit it altogether for the action which has a text button?
cc @kywalker-rh

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx [hunk 6]
```diff
@@ -1,39 +1,76 @@
...
+  toggleElement,
+  variant,
+  isDisabled,
+}) => {
   const [open, setOpen] = React.useState(false);
   const [deleteOpen, setDeleteOpen] = React.useState(false);
   const [viewOpen, setViewOpen] = React.useState(false);
+  const onToggleClick = () => {
+    setOpen(!open);
+  };
```
Comment (andrewballantyne) [inline frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:27]: Help me understand why you took this out of the React render flow? What benefit does this have being a stand alone function? It's only used once -- your "DropdownItem" has an inline `onClick` 🤔 

Is there a flow to which you write your functions that just leads it to be separate and since there is no harm you leave it?

FWIW... Not that it usually matters for `onClick` handlers or even in this use-case -- but separating functions from the component prop callbacks serves to remove the types 🤔 If you used this function twice or managed the prop state it would make more sense. But I am worried about scenarios where you need a return type or props typed, what would you do in those cases?

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx
Comment (andrewballantyne) [inline frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:1]: We should probably relocate this file as it's not tied to a page anymore -- it's a generic usage for two different pages. 

Use cases:
* [import] `frontend/src/pages/pipelines/global/pipelines/GlobalPipelines.tsx`
* [Import] `frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx`
* [Export] `frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx`

Recommend taking this to the concepts folder so it can be used by both more cleanly.

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 3 above)
Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: This would require me to pass down `KebabToggle` from `PipelineSection` and `DropdownToggle` from `GlobalPipelines` to the `toggle` prop of `Dropdown` in `PipelinesPageHeaderActions` and handle toggle actions from `PipelinesSection` and `GlobalPipelines`. Should I go ahead?

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx
Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx:1]: Moved to `concepts`

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 5 above)
Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: Done. I've removed the tooltip for the text button(both disabled and enabled states). I'm currently only showing the tooltip(for disabled state) for the kebab menu. I'm not showing any tooltip for the enabled state for both the kebab menu and the text button.
One doubt: Do we not show the tooltip for both disabled and enabled states or only show the tooltip for the disabled state for the text button? cc @kywalker-rh

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 6 above)
Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: I've inlined this now.

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 3 above)
Comment (christianvogt) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: Do you really need to pass everything down or simply define your own variant prop and switch which toggle you render based on it?

Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: Done. Marking this as Resolved.

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 6 above)
Comment (andrewballantyne) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: @manaswinidas Thanks! Could you help me understand the why though?

Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: I did this for modularity. But a one-liner doesn't quite affect the modularity much. It negatively affects the readability.

Comment (andrewballantyne) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: > It negatively affects the readability.

I am not sure pulling out the inline actions of buttons and similar components is good for readability -- it breaks up the flow. This makes a split reading problem. Reading JSX top to bottom to understand the structure but once I hit a "what does the button click do" you're calling another function causing me to have to "leave the JSX" to understand the implementation -- this adds an unnecessary split in reading.

I've worked a lot on JSX and I have rarely found a problem with inline button functionality, especially for a toggle (1-liner) action, causing an issue. Often times when it happens it's because you're overloading the component's actions with a ton of operations. If you need to do lots of business logic on an action, you should consider what that means for the component -- if the log is too much for inline, then you probably are violating a lot of the effort of what the component is intended to do. Consider splitting up with Hooks or creating new components to manage this logic. 

This is a common problem I find with the team is the separation of the logic. I'll need to write docs to explain what this means and how breaking stuff up into declarative chunks helps with readability.

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 5 above)
Comment (kywalker-rh) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: Good question @manaswinidas. Taking another look at this I would change the tooltip to only being present when the button is disabled, and then I would change the text to:

> To access pipeline server actions, first create a pipeline server.

This prevents the tooltip from getting in the way when performing actions. It also makes it consistent, since we don't have a tooltip for other kebab action menus in the UI.

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 6 above)
Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: I meant Pulling out the inline actions negatively affects the readability.

File: frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx (hunk 5 above)
Comment (manaswinidas) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: I have added the tooltip for the disabled state for both the kebab menu on the Projects page and the button dropdown on the Global Pipelines page.

Comment (kywalker-rh) [reply frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx]: Looks good! Thanks for updating it.

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineServerActions.tsx [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+  DropdownItem,
+  DropdownSeparator,
+  DropdownToggle,
+  KebabToggle,
+  Tooltip,
+} from '@patternfly/react-core';
+import { DeleteServerModal, ViewServerModal } from '~/concepts/pipelines/context';
+
+type PipelineServerActionsProps = {
+  type?: string;
```
Comment (Gkrumbach07) [inline frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineServerActions.tsx:13]: because type can really only be two things, i would constrain the type to an enum or simply `"kebab" | "dropdown"`

If someone wanted to use this component elsewhere, they wouldn't know what to put in type without digging through the component

**Review by Gkrumbach07 — CHANGES_REQUESTED** [review]

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineServerActions.tsx (hunk 7 above)
Comment (christianvogt) [reply frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineServerActions.tsx:13]: Since you'll be updating this, I suggest using `variant` instead of `type` as the prop name to align with PF naming conventions.

**Comment by christianvogt** [comment]
Just the one comment about the prop type. But otherwise lgtm

File: frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineServerActions.tsx (hunk 7 above)
Comment (manaswinidas) [reply frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineServerActions.tsx]: Done

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm
