### PR TITLE
Extract size form out of Spawner Page

### LINKED ISSUE #345: [KFNBC]: "Default" Container size is missing from Notebook controller page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Default" Container size is missing from Notebook controller page. We have only small,Medium and Large sizes present

Other behaviors:

1. Actual container size value has changed:
Example:
JH:
Small:
Limits: 2 CPU, 8Gi Memory Requests: 1 CPU, 8Gi Memory
Medium:
Limits: 6 CPU, 24Gi Memory Requests: 3 CPU, 24Gi Memory

KFNBC:
Small:
Limits: 2 CPU, 2Gi Memory Requests: 1 CPU, 1Gi Memory
Medium:
Limits: 4 CPU, 4Gi Memory Requests: 2 CPU, 2Gi Memory
Large:
Limits: 8 CPU, 8Gi Memory Requests: 4 CPU, 4Gi Memory
Screenshot from 2022-07-25 18-05-49

Screenshot from 2022-07-25 15-56-04

### Expected Behavior

"Default" Container size is should present on Notebook controller page. 

### Steps To Reproduce

Launch the KFNBC spawner page

### Workaround (if any)

_No response_

### OpenShift Version

_No response_

### Openshift Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
RHODS: 1.15.0-qe-nbc
```

### Relevant log output

_No response_

### LINKED ISSUE #418: [Infrastructure] Migrate SpawnerPage Notebook Size Dropdown to it's own Component
Cleanup the Notebook Size dropdown code in the SpawnerPage. (the rest of the cleanup is still tagged for #340)

This split work was done in favour of adding `Default`, but as discussed in #345, we are no longer doing that. But the refactor was good work so we'll keep that effort (which was most of it).

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #418 

## Description

This is an infrastructure PR to extract Size Form out of the Spawner Page which could reduce spawner page size and make it easier to maintain.

## How Has This Been Tested?

Check the sizes dropdown.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by andrewballantyne** [comment]
As discussed on Slack and noted in #345 -- we are no longer doing Default Size. 

@DaoDaoNoCode when you get a chance please update the PR to remove that logic but keep the refactor and update the title of the PR. The work is now tagged for #418

File: frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+  value: string;
+  setValue: (newValue: string) => void;
+};
+
+const SizeSelectField: React.FC<SizeSelectFieldProps> = ({ value, setValue }) => {
+  const [sizeDropdownOpen, setSizeDropdownOpen] = React.useState<boolean>(false);
+  const { dashboardConfig } = React.useContext(AppContext);
+  console.log(value);
+
+  const sizeOptions = React.useMemo(() => {
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx:33]: Don't memo.

---
I'm going to try and explain a few things to help you understand why not to memo in this case. Hopefully this is helpful.

When creating a list of React components, they are in themselves "memoized" by React. That's what the `key` prop is doing. 

When React diffs the DOM on each render to see if it needs to mutate it, it will check static items have the same props they had before -- any divs, form elements, the select that PF mounts, etc... and it will get down to your `sizeOptions`, the things you are memoizing, and each one will have a key that says "I'm Small" or "I'm Large" and React will see that your items are still in `Small, Medium, Large` order, and infer based on the keys that nothing has changed order. It compares the props each has -- "yup, those are the same too". React will do no DOM changes on each render as none of the items have changed in anyway.

What I think you are trying to do, is save yourself cycles on recomputing the React objects -- but we don't really care about that. It's like saving yourself from `1 + 2` on each render -- computers do this incredibly fast. You're probably taking up more memory by using memo than saving on processing power computing the items each render.

The things we need to worry about in the web world are DOM manipulations and API calls. The former is solved FOR US by React -- that's why we use it, no messy jQuery that we need to do it ourselves. The latter is solved by putting loading spinners up when we make API calls and using `useEffect` to wrap those in another thread -- allows an app to be reactive all the time.

Try not to repeat logic that React is doing for us... with each extra line you write, you add more for us to maintain and read around to get to the actual items we need. Go simple first. If we need memos, we can add them later. If you need object references to be pure referentially (ie those passed to a hook dependency array) then feel free to memo. But don't memo unless you found a reason to.

File: frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx [hunk 2]
```diff
@@ -79,8 +78,7 @@ const SpawnerPage: React.FC = React.memo(() => {
     image: undefined,
     tag: undefined,
   });
-  const [sizeDropdownOpen, setSizeDropdownOpen] = React.useState<boolean>(false);
-  const [selectedSize, setSelectedSize] = React.useState<string>('');
+  const [selectedSize, setSelectedSize] = React.useState<string>('Default');
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx:81]: Maybe we just go with something like:

```
const [selectedSize, setSelectedSize] = usePreferredNotebookSize()
```

Then the hook would do the following:
- Look for their preferred notebook size (in Dashboard Config today, in Notebook "tomorrow" - #416)
- If they don't have one -- use the first item in the Dashboard Config `notebookSizes`
- For #303 -- We can wrap the setter function so when they call it with their new selection we store it in localStorage and we add it to our logic for the first bullet (for new pages)

It's all contained, no onus on the SpawnerPage to worry about such things.

File: frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+          ? 'Resources set based on administrator configurations'
+          : `Limits: ${size?.resources?.limits?.cpu || '??'} CPU, ` +
+            `${size?.resources?.limits?.memory || '??'} Memory ` +
+            `Requests: ${size?.resources?.requests?.cpu || '??'} CPU, ` +
+            `${size?.resources?.requests?.memory || '??'} Memory`;
+      return <SelectOption key={name} value={name} description={desc} />;
+    });
+  }, [dashboardConfig]);
+
+  const handleSizeSelection = (e, selection) => {
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx:50]: types please if you're not going to write this inline and let TS infer it from the PF component.

If you want to keep it separate, maybe grab the type from the Select Component:
```
type OnSelect = React.ComponentProps<typeof Select>['onSelect'];
```

You'll then have to handle the `string | SelectOptionObject` cases... and since you know that you are using a `string` value -- you can do `if (typeof selection === 'string') setValue(selection)`

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
I took this as an opportunity to explain some things. Don't be alarmed at the size of the comments 🙂 This was a good effort and we should continue to improve the Spawner Page.

File: frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+    }
+
+    return sizes.map((size) => {
+      const name = size.name;
+      const desc =
+        `Limits: ${size?.resources?.limits?.cpu || '??'} CPU, ` +
+        `${size?.resources?.limits?.memory || '??'} Memory ` +
+        `Requests: ${size?.resources?.requests?.cpu || '??'} CPU, ` +
+        `${size?.resources?.requests?.memory || '??'} Memory`;
+      return <SelectOption key={name} value={name} description={desc} />;
```
Comment (andrewballantyne) [inline frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx:28]: Interesting -- we should probably make our CRD force `requests` and `limits` when they add the items. I logged https://github.com/opendatahub-io/odh-dashboard/issues/420 to manage it.

**Review by andrewballantyne — COMMENTED** [review]
Looking good, just doing some testing now

**Review by andrewballantyne — APPROVED** [review]
